### PR TITLE
Fix issue 1502

### LINKED ISSUE #1502: Node tests systematically fail in ubuntu-24.04-arm (Node 22, gcc, g++, -Db_sanitize=address, Debug)
## Bug Report

`ubuntu-22.04-arm` and `ubuntu-24.04-arm` hosts have been added to CI in this PR https://github.com/versatica/mediasoup/pull/1500.

Somehow, some Node tests systematically fail in `ubuntu-24.04-arm`:

- https://github.com/versatica/mediasoup/actions/runs/13721389481/job/38377476129?pr=1500
- https://github.com/versatica/mediasoup/actions/runs/13721389481/job/38383101706?pr=1500

Note that it's always the same tests:

```
FAIL node/src/test/test-Worker.ts (26.204 s)
  ✓ Worker.workerBin matches mediasoup-worker absolute path (2 ms)
  ✕ createWorker() succeeds (2001 ms)
  ✕ createWorker() with wrong settings rejects with TypeError (2005 ms)
  ✕ worker.updateSettings() succeeds (2002 ms)
  ✕ worker.updateSettings() with wrong settings rejects with TypeError (2001 ms)
  ✕ worker.updateSettings() rejects with InvalidStateError if closed (2001 ms)
  ✓ worker.dump() succeeds (2000 ms)
  ✕ worker.dump() rejects with InvalidStateError if closed (2001 ms)
  ✕ worker.getResourceUsage() succeeds (2001 ms)
  ✕ worker.close() succeeds (2001 ms)
  ✕ Worker emits "died" if worker process died unexpectedly (5002 ms)
  ✕ worker process ignores PIPE, HUP, ALRM, USR1 and USR2 signals (3001 ms)

  ● createWorker() succeeds

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      35 | });
      36 |
    > 37 | test('createWorker() succeeds', async () => {
         | ^
      38 | 	const onObserverNewWorker = jest.fn();
      39 |
      40 | 	mediasoup.observer.once('newworker', onObserverNewWorker);

      at Object.<anonymous> (node/src/test/test-Worker.ts:37:1)

  ● createWorker() with wrong settings rejects with TypeError

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      82 | }, 2000);
      83 |
    > 84 | test('createWorker() with wrong settings rejects with TypeError', async () => {
         | ^
      85 | 	// @ts-expect-error --- Testing purposes.
      86 | 	await expect(mediasoup.createWorker({ logLevel: 'chicken' })).rejects.toThrow(
      87 | 		TypeError

      at Object.<anonymous> (node/src/test/test-Worker.ts:84:1)

  ● worker.updateSettings() succeeds

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      111 | }, 2000);
      112 |
    > 113 | test('worker.updateSettings() succeeds', async () => {
          | ^
      114 | 	const worker = await mediasoup.createWorker();
      115 |
      116 | 	await expect(

      at Object.<anonymous> (node/src/test/test-Worker.ts:113:1)

  ● worker.updateSettings() with wrong settings rejects with TypeError

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      123 | }, 2000);
      124 |
    > 125 | test('worker.updateSettings() with wrong settings rejects with TypeError', async () => {
          | ^
      126 | 	const worker = await mediasoup.createWorker();
      127 |
      128 | 	// @ts-expect-error --- Testing purposes.

      at Object.<anonymous> (node/src/test/test-Worker.ts:125:1)

  ● worker.updateSettings() rejects with InvalidStateError if closed

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      136 | }, 2000);
      137 |
    > 138 | test('worker.updateSettings() rejects with InvalidStateError if closed', async () => {
          | ^
      139 | 	const worker = await mediasoup.createWorker();
      140 |
      141 | 	worker.close();

      at Object.<anonymous> (node/src/test/test-Worker.ts:138:1)

  ● worker.dump() rejects with InvalidStateError if closed

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      164 | }, 2000);
      165 |
    > 166 | test('worker.dump() rejects with InvalidStateError if closed', async () => {
          | ^
      167 | 	const worker = await mediasoup.createWorker();
      168 |
      169 | 	worker.close();

      at Object.<anonymous> (node/src/test/test-Worker.ts:166:1)

  ● worker.getResourceUsage() succeeds

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      174 | }, 2000);
      175 |
    > 176 | test('worker.getResourceUsage() succeeds', async () => {
          | ^
      177 | 	const worker = await mediasoup.createWorker();
      178 |
      179 | 	await expect(worker.getResourceUsage()).resolves.toMatchObject({});

      at Object.<anonymous> (node/src/test/test-Worker.ts:176:1)

  ● worker.close() succeeds

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      184 | }, 2000);
      185 |
    > 186 | test('worker.close() succeeds', async () => {
          | ^
      187 | 	const worker = await mediasoup.createWorker({ logLevel: 'warn' });
      188 | 	const onObserverClose = jest.fn();
      189 |

      at Object.<anonymous> (node/src/test/test-Worker.ts:186:1)

  ● Worker emits "died" if worker process died unexpectedly

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      [198](https://github.com/versatica/mediasoup/actions/runs/13721389481/job/38377476129?pr=1500#step:7:199) | }, 2000);
      199 |
    > 200 | test('Worker emits "died" if worker process died unexpectedly', async () => {
          | ^
      201 | 	let onDied: ReturnType<typeof jest.fn>;
      202 | 	let onObserverClose: ReturnType<typeof jest.fn>;
      203 |

      at Object.<anonymous> (node/src/test/test-Worker.ts:[200](https://github.com/versatica/mediasoup/actions/runs/13721389481/job/38377476129?pr=1500#step:7:201):1)

  ● worker process ignores PIPE, HUP, ALRM, USR1 and USR2 signals

    thrown: "Exceeded timeout of 3000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      308 | // so we just skip this test in Windows.
      309 | if (os.platform() !== 'win32') {
    > 310 | 	test('worker process ignores PIPE, HUP, ALRM, USR1 and USR2 signals', async () => {
          | 	^
      311 | 		const worker = await mediasoup.createWorker({ logLevel: 'warn' });
      312 |
      313 | 		await new Promise<void>((resolve, reject) => {

      at Object.<anonymous> (node/src/test/test-Worker.ts:310:2)
```

```
FAIL node/src/test/test-mediasoup.ts
  ✓ mediasoup.version matches version field in package.json (1 ms)
  ✕ setLoggerEventListeners() works (2001 ms)
  ✓ mediasoup.getSupportedRtpCapabilities() returns the mediasoup RTP capabilities (2 ms)
  ✓ parseScalabilityMode() works (2 ms)

  ● setLoggerEventListeners() works

    thrown: "Exceeded timeout of 2000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      18 | });
      19 |
    > 20 | test('setLoggerEventListeners() works', async () => {
         | ^
      21 | 	const onDebug = jest.fn();
      22 |
      23 | 	mediasoup.setLogEventListeners({

      at Object.<anonymous> (node/src/test/test-mediasoup.ts:20:1)
```

## TODO

- Fix the issue (if possible).
- Uncomment the job in CI `mediasoup-node.yaml`

### PR DESCRIPTION
**Pull request by ibc**
Fixes #1502

## Details

- `worker/Dockerfile`: Use Ubuntu 24.04 and Node 22.
- Giving up since `createWorker()` takes amazingly long (cannot anticipate it) in `ubuntu-24.04-arm` Debug build type with ASAN (`-Db_sanitize=address`), so skip node tests on it.
- Cosmetic and typo fixes.

### CODE REVIEW

**Comment by ibc** [comment]
@nazar-pc you know proper syntax for this?

```yaml
if: ${{ (!matrix.build.skip-test-in-debug-build-type) || (matrix.build-type != "Debug") }}
```

It fails:

> [Invalid workflow file: .github/workflows/mediasoup-node.yaml#L147](https://github.com/versatica/mediasoup/actions/runs/13737284806/workflow)
The workflow is not valid. .github/workflows/mediasoup-node.yaml (Line: 147, Col: 13): Unexpected symbol: '"Debug"'. Located at position 72 within expression: (!matrix.build.skip-test-in-debug-build-type) || (matrix.build-type != "Debug")

**Comment by ibc** [comment]
> @nazar-pc you know proper syntax for this?
> 
> ```yaml
> if: ${{ (!matrix.build.skip-test-in-debug-build-type) || (matrix.build-type != "Debug") }}
> ```
> 
> It fails:
> 
> > [Invalid workflow file: .github/workflows/mediasoup-node.yaml#L147](https://github.com/versatica/mediasoup/actions/runs/13737284806/workflow)
> > The workflow is not valid. .github/workflows/mediasoup-node.yaml (Line: 147, Col: 13): Unexpected symbol: '"Debug"'. Located at position 72 within expression: (!matrix.build.skip-test-in-debug-build-type) || (matrix.build-type != "Debug")

Ok, ChatGPT helped me and it works: https://github.com/versatica/mediasoup/pull/1504/commits/588eda4e0ce599d30de3e25028591a2f8ffa39e3

**Comment by ibc** [comment]
OMG the condition doesn't work... the job is still running `npm run test:node`:

https://github.com/versatica/mediasoup/actions/runs/13737319247/job/38422572050?pr=1504

**Comment by ibc** [comment]
> OMG the condition doesn't work... the job is still running `npm run test:node`:
> 
> https://github.com/versatica/mediasoup/actions/runs/13737319247/job/38422572050?pr=1504

no no, it didn't run! it's ok! merging soon!

File: node/src/test/test-Worker.ts [hunk 1]
```diff
@@ -322,9 +322,9 @@ if (os.platform() !== 'win32') {
 			setTimeout(() => {
 				expect(worker.closed).toBe(false);
 
-				worker.close();
 				worker.on('subprocessclose', resolve);
+				worker.close();
 			}, 2000);
 		});
-	}, 3000);
+	}, 4000);
```
Comment (nazar-pc) [inline node/src/test/test-Worker.ts:329]: This is really not a solution IMHO, I'd leave a TODO to figure out the reason and fix it. Even 2 or 3 seconds seems VERY slow.

Comment (ibc) [reply node/src/test/test-Worker.ts:329]: This is not fixing anything. It's just for consistency. All tests that run createWorker() *inside* have 2000ms timeout and here we do that plus we run a timer of 2 seconds inside, and hence the 4000ms. I insist, this change is not fixing anything that was failing, it's just for consistency.

Comment (nazar-pc) [reply node/src/test/test-Worker.ts:329]: This whole test is honestly just racy and strange.

You send 5 signals in a row with expectation that none of them do anything, then wait for 2 more seconds (would be nice to have something more deterministic so tests run faster) and then wait for up to two more seconds for it to actually exit after calling `worker.close()`.

Not only the inner 2 seconds seems arbitrary:
* is there a deterministic way to know this?
* what is even the reason for testing these signals?
  * note that there are many more signals, which are not tested

For deterministic part I think it is possible, assuming signals arrive in order to the process:
* send 5 signals and call `worker.close()` right after that without any delay (effectively 6th signal, `SIGTERM`)
* check exit code of the worker process to see if it existed successfully (due to `SIGTERM`) or some other reason

Then there will be no need to have lower-level timeout, which will save at least 2 seconds on this particular test.

Right now the only thing that is checked is `this.#child.killed` and if so then it is considered successful, but if process exit was graceful, the status code must also be `0` and if it is not, then something wrong did actually happen.

So I think the whole `child.on('exit', ...)` handling needs refactoring.

**Review by jmillan — APPROVED** [review]

File: node/src/test/test-Worker.ts (hunk 1 above)
Comment (ibc) [reply node/src/test/test-Worker.ts:329]: I will come back to this tomorrow or Monday but:

No, there is no deterministic way to know if the worker ignored a signal because signals are not sent synchronously to processes so we have to await some time before we check if any of those signals closed the process (they shouldn't). So we cannot send a signal and **immediately** send some message to the worker to see if it's alive, because the message could arrive before the signal.

Comment (nazar-pc) [reply node/src/test/test-Worker.ts:329]: Okay, what are we testing here specifically then?

Comment (ibc) [reply node/src/test/test-Worker.ts:329]: We are testing that those signals don't close the process. There are other tests that assert that other types of signals do close the process. In the latter we don't need to run any timer.

Comment (ibc) [reply node/src/test/test-Worker.ts:329]: > but if process exit was graceful, the status code must also be 0 and if it is not, then something wrong did actually happen.
> 
> So I think the whole child.on('exit', ...) handling needs refactoring.

I don't understand what exactly is wrong here. mediasoup Node worker.close() effectively closes the worker process by sending a SIGTERM signal end of course expected exit code is 0 (nothing was wrong). The user can of course kill the worker process by their own by sending same signal. If so, mediasoup Node emits "close" on the Worker instance.

Comment (nazar-pc) [reply node/src/test/test-Worker.ts:329]: Why is it important that these signals specifically do not close the process?

There are a lot more signals possible, which are not tested: https://www.man7.org/linux/man-pages/man7/signal.7.html#:~:text=Linux%20supports%20the%20standard%20signals%20listed%20below

And no, I'm not suggesting to add more signals to the test :slightly_smiling_face:

Comment (ibc) [reply node/src/test/test-Worker.ts:329]: Years ago I realized that mediasoup crashed due to PIPE signals specially on MacOS and that was a LEGITIMATE signal that the OS sent to a process when something LEGITIMATE related to sockets happened. So we MUST ignore PIPE signals. The other signals? ¯\_(ツ)_/¯
