### PR TITLE
Consumer: Fix sequence number gap

### LINKED ISSUE #1069: Large packet loss when estimated bandwidth is close to the lowest SVC layer
## Bug Report
When the estimated bandwidth is close to the lowest SVC layer, the allocated layer fluctuates between 0:0 and -1:-1. Concurrently, we observed large packet loss spikes at receiver side (80-100%) that didn't happen when using VP8/Simulcast in the same conditions. Analyzing the captured RTP packets, there are large seqno jumps that could explain the packet loss:

nopatch
[nopatch.pcapng.gz](https://github.com/versatica/mediasoup/files/11298614/nopatch.pcapng.gz)

The issue can be reproduced consuming 1 VP9 stream and calling `transport.setMaxOutgoingBitrate(80000)` (set a number close to the lowest encoded SVC layer).

### PR DESCRIPTION
**Pull request by jmillan**
Drop the given sequence number if the RTP packet cannot be forwarded.

Fixes  #1069 

By not doing so, we are incorrectly generating non legitimate sequence number jumps which involves:

- The other end requesting NACKs for packets that do not exist, and us processing them.
- The other end waiting for those packets that will never arrive.
- Possible implications an jitter buffer and decoding level.

This problem is very apparent when using BWE and the available BW is low enough to discard a lot of packets, or when the outgoing bitrate is manually set low enough too.

### CODE REVIEW

File: worker/src/Channel/ChannelSocket.cpp [hunk 1]
```diff
@@ -256,10 +261,14 @@ namespace Channel
...
 			this->channelWriteFn(payload, payloadLen, this->channelWriteCtx);
 		}
-		else
+		else if (this->producerSocket)
 		{
 			this->producerSocket->Write(payload, payloadLen);
 		}
+		else
+		{
+			MS_DEBUG_DEV("sending Channel message: %s", payload);
```
Comment (ibc) [inline worker/src/Channel/ChannelSocket.cpp]: What is the purpose of this log that says something that in fact is not happening?

File: worker/src/RTC/SimulcastConsumer.cpp [hunk 2]
```diff
@@ -777,6 +781,7 @@ namespace RTC
 				packet->logger.Dropped(RtcLogger::RtpPacket::DropReason::NOT_A_KEYFRAME);
 #endif
 
+				this->rtpSeqManager->Drop(packet->GetSequenceNumber());
 				return;
```
Comment (ibc) [inline worker/src/RTC/SimulcastConsumer.cpp]:
```suggestion
				this->rtpSeqManager->Drop(packet->GetSequenceNumber());

				return;
```

File: worker/src/RTC/SimulcastConsumer.cpp [hunk 3]
```diff
@@ -804,19 +809,20 @@ namespace RTC
 			packet->logger.Dropped(RtcLogger::RtpPacket::DropReason::NOT_A_KEYFRAME);
 #endif
 
+			this->rtpSeqManager->Drop(packet->GetSequenceNumber());
 			return;
```
Comment (ibc) [inline worker/src/RTC/SimulcastConsumer.cpp:814]:
```suggestion
			this->rtpSeqManager->Drop(packet->GetSequenceNumber());

			return;
```

File: worker/src/RTC/SimulcastConsumer.cpp [hunk 4]
```diff
@@ -935,6 +941,7 @@ namespace RTC
 					packet->logger.Dropped(RtcLogger::RtpPacket::DropReason::TOO_HIGH_TIMESTAMP_EXTRA_NEEDED);
 #endif
 
+					this->rtpSeqManager->Drop(packet->GetSequenceNumber());
 					return;
```
Comment (ibc) [inline worker/src/RTC/SimulcastConsumer.cpp]:
```suggestion
					this->rtpSeqManager->Drop(packet->GetSequenceNumber());

					return;
```

File: worker/test/src/RTC/TestSimpleConsumer.cpp [hunk 5]
```diff
@@ -0,0 +1,283 @@
...
+        0x00, 0x00, 0x00, 0x05
+    };
+	// clang-format on
+
+	SECTION("RTP packets are not forwarded when the consumer is not active")
+	{
+		auto* listener = new ConsumerListener();
+		auto* consumer = CreateConsumer(listener);
+
+		auto* rtpStream = CreateRtpStreamRecv();
```
Comment (ibc) [inline worker/test/src/RTC/TestSimpleConsumer.cpp]:
```suggestion
		auto* listener  = new ConsumerListener();
		auto* consumer  = CreateConsumer(listener);
		auto* rtpStream = CreateRtpStreamRecv();
```

**Review by ibc — COMMENTED** [review]
I'm amazed that this fix looks too obvious to never have realized of it. I mean, we were literally dropping packets in MANY SCENARIOS without dropping then in SeqManager. How is possible that we never noticed it?

Please add entry in CHANGELOG.

Also minimal cosmetic changes.

And ASAN checks are failing in CI.

**Comment by ibc** [comment]
> Fixes #1069

Fixes #1069 or fixes #1070 or both?

**Comment by ibc** [comment]
I'm updating the branch with pending changes in v3.

**Comment by ibc** [comment]
> And ASAN checks are failing in CI.

All those are caused by the new `TestSimpleConsumer.cpp` file.

File: worker/src/Channel/ChannelSocket.cpp (hunk 1 above)
Comment (jmillan) [reply worker/src/Channel/ChannelSocket.cpp]: I've created a new `ChannelSocket` constructor that does not received callbacks (RUST) nor file descriptors (Node). Just for testing purposes. So when sending something out it will just log it, nothing else.

Comment (ibc) [reply worker/src/Channel/ChannelSocket.cpp]: That's what I meant: why is it logging that it is sending a message if it's not doing it?

File: worker/test/src/RTC/TestSimpleConsumer.cpp [hunk 6]
```diff
@@ -10,7 +10,11 @@
 
 using namespace RTC;
 
-const uint8_t PayloadType = 111;
+const uint8_t PayloadType       = 111;
+auto* channelMessageRegistrator = new ChannelMessageRegistrator();
```
Comment (ibc) [inline worker/test/src/RTC/TestSimpleConsumer.cpp:14]: const?

File: worker/test/src/RTC/TestSimpleConsumer.cpp [hunk 7]
```diff
@@ -10,7 +10,11 @@
...
+auto* channelSocket             = new Channel::ChannelSocket();
+auto* channelNotifier           = new Channel::ChannelNotifier(channelSocket);
+auto shared                     = Shared(channelMessageRegistrator, channelNotifier);
```
Comment (ibc) [inline worker/test/src/RTC/TestSimpleConsumer.cpp:17]: const?

**Review by ibc — APPROVED** [review]

File: worker/src/Channel/ChannelSocket.cpp (hunk 1 above)
Comment (jmillan) [reply worker/src/Channel/ChannelSocket.cpp]: It's like a mock. Shall I change the text to "TEST -- sending Channel message..." or alike?

Give me some time and I'll deal with it later with a better approach.

Comment (ibc) [reply worker/src/Channel/ChannelSocket.cpp]: We have condition blocks above in the same if else section in which we do send a message but don't log anything and here we are adding a block that doesn't send a message and logs that it has sent a message. I would just remove that log and that's all.

Said that, I don't remember if we have some macro/define that just exists during worker tests but if so, such a new constructor could be wrapped into a macro condition that checks whether such a define exists.

Comment (jmillan) [reply worker/src/Channel/ChannelSocket.cpp]: Fixed in the lat commit. Such constructor is only compiled if `MS_TEST` define is enabled.

File: worker/test/src/RTC/TestSimpleConsumer.cpp (hunk 7 above)
Comment (jmillan) [reply worker/test/src/RTC/TestSimpleConsumer.cpp:17]: Nop, as this is provided to `SimpleConsumer` which expects a non const `Shared`. We can probably change that and pass a const `Shared` instead.

Let's please use another PR to do so.

**Review by ibc — APPROVED** [review]
