### PR TITLE
Rust: Don't log error if `xxx.close()` fails due to channel closed

### LINKED ISSUE #1396: [Rust] Error log “XXX closing failed on drop: Channel already closed”
### Your environment

- mediasoup version: f1973891e792eab40ebda54deed163d04aa1ead4
- mediasoup-client version: N/A

### Issue description
When dynamically creating/deleting Workers, I get a lot of “XXXXXX closing failed on drop: Channel already closed” error logs.
I think this is useless with no way to fix it.

The test code also receives many error logs.
`RUST_LOG=error cargo test -- --nocapture`

If you're open for this I'd be happy to file a PR

### PR DESCRIPTION
**Pull request by ibc**
Fixes #1396

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

File: rust/src/router.rs [hunk 1]
```diff
@@ -404,10 +404,17 @@ impl Inner {
...
                 let channel = self.channel.clone();
                 let request = RouterCloseRequest { router_id: self.id };
+
                 self.executor
                     .spawn(async move {
-                        if let Err(error) = channel.request("", request).await {
-                            error!("router closing failed on drop: {}", error);
+                        match channel.request("", request).await {
+                            Err(RequestError::ChannelClosed) => {
+                                println!("router closing failed on drop: Channel already closed");
```
Comment (nazar-pc) [inline rust/src/router.rs]: Did you mean `error!()` or `warn!()` or other log level?

**Review by nazar-pc — CHANGES_REQUESTED** [review]
This doesn't fix anything, it just replaces `error!()` log level with `println!()` for some reason for one of the error cases. What did you actually mean to do here?

File: rust/src/router.rs (hunk 1 above)
Comment (nazar-pc) [reply rust/src/router.rs]: Or maybe `debug!()` or `trace!()`? `println!()` will simply write it to standard output, which is even more annoying than going through logger.

Comment (ibc) [reply rust/src/router.rs]: Just run `RUST_LOG=error cargo test -- --nocapture` and you will see tons of those false errors. Calling `xxxx.close()` on something that is already closed should never log an **error**.

Comment (ibc) [reply rust/src/router.rs]: What I want is to NOT use `error!()` or `warn!()` when there is no real error.

Comment (nazar-pc) [reply rust/src/router.rs]: I see, make it `debug!()` then, so it can still be seeing if desired, but not shown with a typical info log level.

Comment (ibc) [reply rust/src/router.rs]: Done here: https://github.com/versatica/mediasoup/pull/1560/commits/69d8fc6d3cf3b067b63dbc4196d2f0287ed5400c

**Review by nazar-pc — APPROVED** [review]
