### PR TITLE
`RtpParameters`: add `msid` optional field

### LINKED ISSUE #1633: `cargo build` fails in latest macOS due to removed macro `_LIBCPP_ENABLE_ASSERTIONS`
I updated my Xcode Command Line Tools or whatver and now I cannot build mediasoup Rust. `cargo build` fails as follows:

```
Found ninja-1.10.2.git.kitware.jobserver-1 at /Volumes/src-cs/mediasoup/target/debug/build/mediasoup-sys-a3e37132768c4096/out/out/pip_meson_ninja/bin/ninja
  [1/49] Compiling C++ object subprojects/flatbuffers-24.3.25/libswift_generator.a.p/grpc_src_compiler_swift_generator.cc.o
  FAILED: subprojects/flatbuffers-24.3.25/libswift_generator.a.p/grpc_src_compiler_swift_generator.cc.o 
  c++ -Isubprojects/flatbuffers-24.3.25/libswift_generator.a.p -Isubprojects/flatbuffers-24.3.25 -I../../../../../../worker/subprojects/flatbuffers-24.3.25 -I../../../../../../worker/subprojects/flatbuffers-24.3.25/include -I../../../../../../worker/subprojects/flatbuffers-24.3.25/grpc -fdiagnostics-color=always -D_LIBCPP_ENABLE_ASSERTIONS=1 -std=c++17 -O0 -g -DFLATBUFFERS_LOCALE_INDEPENDENT=true -fsigned-char -MD -MQ subprojects/flatbuffers-24.3.25/libswift_generator.a.p/grpc_src_compiler_swift_generator.cc.o -MF subprojects/flatbuffers-24.3.25/libswift_generator.a.p/grpc_src_compiler_swift_generator.cc.o.d -o subprojects/flatbuffers-24.3.25/libswift_generator.a.p/grpc_src_compiler_swift_generator.cc.o -c ../../../../../../worker/subprojects/flatbuffers-24.3.25/grpc/src/compiler/swift_generator.cc
  In file included from ../../../../../../worker/subprojects/flatbuffers-24.3.25/grpc/src/compiler/swift_generator.cc:23:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/map:577:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/equal.h:13:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__algorithm/comp.h:12:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:49:6: error: "_LIBCPP_ENABLE_ASSERTIONS has been removed, please use _LIBCPP_HARDENING_MODE instead"
     49 | #    error "_LIBCPP_ENABLE_ASSERTIONS has been removed, please use _LIBCPP_HARDENING_MODE instead"
        |      ^
  1 error generated.
  [2/49] Compiling C++ object subprojects/flatbuffers-24.3.25/libpython_generator.a.p/grpc_src_compiler_python_generator.cc.o
```

- macOS: 15.6.1 (ARM M4)
- Xcode: 26.0.1
- MacOSX26.0.sdk

### PR DESCRIPTION
**Pull request by ibc**
# Details

- Specification: [RFC 8830](https://datatracker.ietf.org/doc/html/rfc8830)
- Corresponding PR in mediasoup-client: https://github.com/versatica/mediasoup-client/pull/352
- Add `msid` optional string field to `RtpParameters`.

## Bonus tracks

- Bump up Meson from 1.5.0 to 1.9.1. Fixes #1633

# TODO

- [x] Website documentation.

### CODE REVIEW

File: node/src/rtpParametersFbsUtils.ts [hunk 1]
```diff
@@ -494,12 +495,12 @@ export function parseRtpEncodingParameters(
 ): RtpEncodingParameters {
 	return {
 		ssrc: data.ssrc() ?? undefined,
-		rid: data.rid() ?? undefined,
+		rid: data.rid() || undefined,
```
Comment (ibc) [inline node/src/rtpParametersFbsUtils.ts:498]: This is because if `rid` is empty string we want it to become `undefined`. Same in all similar changes below.

File: worker/src/RTC/RtpDictionaries/RtpParameters.cpp [hunk 2]
```diff
@@ -105,11 +105,6 @@ namespace RTC
 		if (data->mid())
 		{
 			this->mid = data->mid()->str();
-
-			if (this->mid.empty())
-			{
-				MS_THROW_TYPE_ERROR("empty mid");
-			}
```
Comment (ibc) [inline worker/src/RTC/RtpDictionaries/RtpParameters.cpp:112]: This was a terrible idea. In the copy constructor we may perfectly copy from a `RtpParameters` instance whose `mid` was not set and hence it has empty string as value, and this block of code would literally throw. There is no reason for this check here. If `mid` is not set then it is an empty string in `RtpParameters`, but then, when moving it to Node/Rust, we avoid serializing it so we are good. This check was buggy and totally unneeded.

File: worker/tasks.py [hunk 3]
```diff
@@ -51,7 +51,7 @@
 NUM_CORES = len(os.sched_getaffinity(0)) if hasattr(os, 'sched_getaffinity') else os.cpu_count();
 PYTHON = os.getenv('PYTHON') or sys.executable;
 MESON = os.getenv('MESON') or f'{PIP_MESON_NINJA_DIR}/bin/meson';
-MESON_VERSION = os.getenv('MESON_VERSION') or '1.5.0';
+MESON_VERSION = os.getenv('MESON_VERSION') or '1.9.1';
```
Comment (ibc) [inline worker/tasks.py:54]: Unrelated change that fixes https://github.com/versatica/mediasoup/issues/1633.

**Review by jmillan — APPROVED** [review]

File: worker/tasks.py (hunk 3 above)
Comment (GEverding) [reply worker/tasks.py:54]: That allowed me to compile. Can we get that brought into main soon?

Comment (ibc) [reply worker/tasks.py:54]: It's merged now
