### PR TITLE
Fix test-node-sctp connection timeout on Windows

### LINKED ISSUE #501: [Windows] test-node-sctp failed
### Your environment

- Operating system: Windows 10
- Node version:v10.19.0
- npm version:6.13.4
- gcc/clang version:
- mediasoup version:3.6.25
- mediasoup-client version:

### Issue description

When running yarn test, the test-node-sctp is failing all the time on Windows as the reason is connection timeout.
It's OK on macOS and Linux, I closed the firewall but the same result.

I find this issue from official node repo https://github.com/nodejs/node/issues/14900 

Use 127.0.0.1 as `listenIp` and `annoucedIp` works for me

### PR DESCRIPTION
**Pull request by universeroc**
Fixes https://github.com/versatica/mediasoup/issues/501

### CODE REVIEW

**Review by ibc — CHANGES_REQUESTED** [review]
Thanks. Please remove the `announcedIp` line. No longer needed then.

File: test/test-node-sctp.js [hunk 1]
```diff
@@ -25,8 +25,7 @@ beforeAll(async () =>
 	router = await worker.createRouter();
 	transport = await router.createPlainTransport(
 		{
-			listenIp       : '0.0.0.0',
-			announcedIp    : '127.0.0.1',
+			listenIp       : '127.0.0.1',  // https://github.com/nodejs/node/issues/14900
```
Comment (ibc) [inline test/test-node-sctp.js]:
```suggestion
			listenIp       : '127.0.0.1', // https://github.com/nodejs/node/issues/14900
```

**Comment by ibc** [comment]
Thanks
