### PR TITLE
Rtcp enhancements

### LINKED ISSUE #907: An overflow and crash risk in RTC::Transport::SendRtcp
### Your environment

- Operating system: Linux
- Node version:
- npm version:
- gcc/clang version:
- mediasoup version: v3 recent version
- mediasoup-client version:

### Issue description

In `RTC::Transport::SendRtcp()`, when serializing the compound RTCP packet for `mapProducers`, there's a overflow and crash risk: `packet->GetSize()`  will return default `0` forever if `packet->Serialize(RTC::RTCP::Buffer)` was not called before it :
```
	void Transport::SendRtcp(uint64_t nowMs)
	{
		MS_TRACE();

		std::unique_ptr<RTC::RTCP::CompoundPacket> packet{ nullptr };

		for (auto& kv : this->mapConsumers)
		{
			auto* consumer = kv.second;

			for (auto* rtpStream : consumer->GetRtpStreams())
			{
				// Reset the Compound packet.
				packet.reset(new RTC::RTCP::CompoundPacket());

				consumer->GetRtcp(packet.get(), rtpStream, nowMs);

				// Send the RTCP compound packet if there is a sender report.
				if (packet->HasSenderReport())
				{
					packet->Serialize(RTC::RTCP::Buffer);
					SendRtcpCompoundPacket(packet.get());
				}
			}
		}

		// Reset the Compound packet.
		packet.reset(new RTC::RTCP::CompoundPacket());

		for (auto& kv : this->mapProducers)
		{
			auto* producer = kv.second;

			producer->GetRtcp(packet.get(), nowMs);

			// One more RR would exceed the MTU, send the compound packet now.
			/*
			 * The if condition below will not be met forever, because the GetSize() always return 0.-------------------
			*/
			if (packet->GetSize() + sizeof(RTCP::ReceiverReport::Header) > RTC::MtuSize)
			{
				//The following code will not be executed.---------------------------
				packet->Serialize(RTC::RTCP::Buffer);
				SendRtcpCompoundPacket(packet.get());

				// Reset the Compound packet.
				packet.reset(new RTC::RTCP::CompoundPacket());
			}
		}

		if (packet->GetReceiverReportCount() != 0u)
		{
			/*
			 * Finally, if the mapProducers's elements amout is enough large, all producers's data serialized into 
			 * the buffer together, then it will overflow.
			*/
			packet->Serialize(RTC::RTCP::Buffer);
			SendRtcpCompoundPacket(packet.get());
		}
	}
```
Because `packet->GetSize()` returned the `size`'s value only, but didn't calculated the `size`'s value:
```
	namespace RTCP
	{
		class CompoundPacket
		{
		public:
			CompoundPacket() = default;

		public:
			const uint8_t* GetData() const
			{
				return this->header;
			}
			size_t GetSize() const
			{
				return this->size;
			}
			......
			......   

```
The `size`'s value was calculated in `CompoundPacket::Serialize()` :
```
namespace RTC
{
	namespace RTCP
	{
		/* Instance methods. */

		void CompoundPacket::Serialize(uint8_t* data)
		{
			MS_TRACE();

			this->header = data;

			// Calculate the total required size for the entire message.
			if (HasSenderReport())
			{
				this->size = this->senderReportPacket.GetSize();

				if (this->receiverReportPacket.GetCount() != 0u)
				{
					this->size += ReceiverReport::HeaderSize * this->receiverReportPacket.GetCount();
				}
			}
			// If no sender nor receiver reports are present send an empty Receiver Report
			// packet as the head of the compound packet.
			else
			{
				this->size = this->receiverReportPacket.GetSize();
			}
			......
			......
```
If the `mapProducers element amount` is enough large, then `packet->Serialize(RTC::RTCP::Buffer);` will OVERFLOW: the `RTC::RTCP::Buffer` can't hold all serialized data and some adjoining important data  will be damaged by OVERFLOW.

I modified it like below, calling `packet->Serialize(RTC::RTCP::Buffer)` before calling `packet->GetSize()`:
```
	void Transport::SendRtcp(uint64_t nowMs)
	{
		MS_TRACE();

		std::unique_ptr<RTC::RTCP::CompoundPacket> packet{ nullptr };

		for (auto& kv : this->mapConsumers)
		{
			auto* consumer = kv.second;

			for (auto* rtpStream : consumer->GetRtpStreams())
			{
				// Reset the Compound packet.
				packet.reset(new RTC::RTCP::CompoundPacket());

				consumer->GetRtcp(packet.get(), rtpStream, nowMs);

				// Send the RTCP compound packet if there is a sender report.
				if (packet->HasSenderReport())
				{
					packet->Serialize(RTC::RTCP::Buffer);
					SendRtcpCompoundPacket(packet.get());
				}
			}
		}

		// Reset the Compound packet.
		packet.reset(new RTC::RTCP::CompoundPacket());

		for (auto& kv : this->mapProducers)
		{
			auto* producer = kv.second;

			producer->GetRtcp(packet.get(), nowMs);
			packet->Serialize(RTC::RTCP::Buffer); // Move Here----------------------------

			// One more RR would exceed the MTU, send the compound packet now.
			if (packet->GetSize() + sizeof(RTCP::ReceiverReport::Header) > RTC::MtuSize)
			{
				SendRtcpCompoundPacket(packet.get());

				// Reset the Compound packet.
				packet.reset(new RTC::RTCP::CompoundPacket());
			}
		}

		if (packet->GetReceiverReportCount() != 0u)
		{
			packet->Serialize(RTC::RTCP::Buffer);
			SendRtcpCompoundPacket(packet.get());
		}
	}
```

### PR DESCRIPTION
**Pull request by jmillan**
Fixes #907

Enhances RTCP compound packet sending:
* It does now fill the RTCP compound packet as much as possible before sending:
  * Reduces the number of RTCP packets sent and the overhead given by smaller packets.
  * Reduces RTCP compound packet memory allocations since they are used much less now.

**NOTE:** Please read the changes commit by commit.

### CODE REVIEW

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
This was merged without changes in CHANGELOG :(

**Comment by jmillan** [comment]
Changelog updated in the next commit.

File: worker/include/RTC/RTCP/ReceiverReport.hpp [hunk 1]
```diff
@@ -190,12 +199,12 @@ namespace RTC
...
-				for (auto* report : reports)
-				{
-					size += report->GetSize();
-				}
+				// A serialized packet can contain a maximum of 31 reports.
+				// If number of reports exceeds 31 then the required number of packets
+				// will be serialized which will take the size calculated below.
+				size_t size = (Packet::CommonHeaderSize + 4u /* this->ssrc */) *
+				              ((this->GetCount() / MaxReportsPerPacket) + 1);
+				size += ReceiverReport::HeaderSize * this->GetCount();
```
Comment (ibc) [inline worker/include/RTC/RTCP/ReceiverReport.hpp:207]: Can you explain in detail this math?

Comment (jmillan) [reply worker/include/RTC/RTCP/ReceiverReport.hpp:207]: A Receiver Report packet is composed by:

* RTCP common header  (Packet::CommonHeaderSize).
* SSRC of the packet sender. (4 bytes)
* Up to 31 reports. (Each report size is ReceiverReport::HeaderSize )

This method returns the size needed to represent all it's content.

Comment (ibc) [reply worker/include/RTC/RTCP/ReceiverReport.hpp:207]: image

Why is (commonHeader size + 4) being multiplied by ((number of reports divided by max reports per packet) + 1)?

Comment (jmillan) [reply worker/include/RTC/RTCP/ReceiverReport.hpp:207]: We are calculating there how many receiver report packets (Common header + SSRC) we need, considering  our packet instance packet can hold more than 31 receiver reports and the the maximum reports a serialized receiver report packet can contain  is 31 (limit given by the 'count' header field in the RTCP common header).
