### PR TITLE
Node: Add new worker.on('subprocessclose') to fix Node tests

### LINKED ISSUE #1306: Issues in Node tests
Here some issues in Node tests:

- [ ] CI failing due to aborted `PRODUCER_PAUSE` channel request: https://github.com/versatica/mediasoup/actions/runs/7448459449/job/20262892577?pr=1305
- [ ] `npm run test:node -- --testPathPattern test-ActiveSpeakerObserver` fails with:
  ```
  Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  PROCESSWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-ActiveSpeakerObserver.ts:26:31
      at node/src/test/test-ActiveSpeakerObserver.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-ActiveSpeakerObserver.ts:4:12)
      at Object.<anonymous> (node/src/test/test-ActiveSpeakerObserver.ts:25:23)


  ●  PIPEWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

          at Array.reduce (<anonymous>)
      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-ActiveSpeakerObserver.ts:26:31
      at node/src/test/test-ActiveSpeakerObserver.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-ActiveSpeakerObserver.ts:4:12)
      at Object.<anonymous> (node/src/test/test-ActiveSpeakerObserver.ts:25:23)
  ```
- [ ] `npm run test:node -- --testPathPattern "test-PipeTransport.ts"` fails with:
  ```
  Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  PROCESSWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-PipeTransport.ts:171:32
      at node/src/test/test-PipeTransport.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-PipeTransport.ts:4:12)
      at Object.<anonymous> (node/src/test/test-PipeTransport.ts:170:23)


  ●  PIPEWRAP

      339 | 		);
      340 |
    > 341 | 		this.#child = spawn(
          | 		                   ^
      342 | 			// command
      343 | 			spawnBin,
      344 | 			// args

          at Array.reduce (<anonymous>)
      at new Worker (node/src/Worker.ts:341:22)
      at Object.<anonymous> (node/src/index.ts:64:17)
      at node/src/index.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/index.ts:4:12)
      at Object.createWorker (node/src/index.ts:38:12)
      at node/src/test/test-PipeTransport.ts:171:32
      at node/src/test/test-PipeTransport.ts:8:71
      at Object.<anonymous>.__awaiter (node/src/test/test-PipeTransport.ts:4:12)
      at Object.<anonymous> (node/src/test/test-PipeTransport.ts:170:23)
  ```

Probably many similar ones if we run each test file separately.

NOTE: Yes, I added `--detectOpenHandles` to `jest` command, but it should work fine.

### PR DESCRIPTION
**Pull request by ibc**
Fixes #1306

### Details

- Problem only happened when running a test file separately (it worked by accident when running all tests together as usual).
- Problem was that the `ChildProcess` object in `Worker` (the `this.#child` member) remains open for a bit until it emits 'close' event, which is emitted after 'exit' event or after 'error' event.
- But we didn't await for that event at all since out `worker.close()` method is sync and we do not care of what is happening in the subprocess after calling it. And this is good. However it's bad for tests if we use `--detectOpenHandles` in Jest command.
- Here we have added a new 'subprocessclose' event in `Worker` which is emitted when the worker subprocess has closed. It may be (and it will be) emitted AFTER calling `worker.close()` but not immediately after it.
- This event is basically useful for scenarios like testing where we want to verify that nothing remains running/open when a test is finished.
- Also added a `worker.subprocessClosed` getter.
- Removed an ugly `setTimeout` in `Channel::close()` method. If the app wants to get the very latest notifications/logs from worker when closing it, use the above event to wait for final closure.

### Bonus Tracks

- Be consistent in command line arguments and always use `--option-foo bar` instead of `--option-foo=bar`.
- Make `tasks.py` and `Makefile` more resistant to paths with spaces.

### CODE REVIEW

File: node/src/test/test-DirectTransport.ts [hunk 1]
```diff
@@ -138,7 +144,7 @@ test('dataProducer.send() succeeds', async () => {
 			);
 		});
 
-		sendNextMessage();
+		await sendNextMessage();
```
Comment (ibc) [inline node/src/test/test-DirectTransport.ts:147]: I have some hope that this will fix this CI random failure: https://github.com/versatica/mediasoup/actions/runs/7448459449/job/20262892577?pr=1305

File: node/src/test/test-ActiveSpeakerObserver.ts [hunk 2]
```diff
@@ -27,8 +27,14 @@ beforeEach(async () => {
 	ctx.router = await ctx.worker.createRouter({ mediaCodecs: ctx.mediaCodecs });
 });
 
-afterEach(() => {
+afterEach(async () => {
 	ctx.worker?.close();
+
+	if (ctx.worker?.subprocessClosed === false) {
```
Comment (ibc) [inline node/src/test/test-ActiveSpeakerObserver.ts:33]: We check `=== false` because if the worker failed to be created in `beforeEach` hook, then `ctx.worker` won't exist here so `ctx.worker?.subprocessClosed` will return `undefined`. In that case we do NOT want to await for any event.

File: node/src/Worker.ts [hunk 3]
```diff
@@ -545,15 +575,8 @@ export class Worker<
...
-		if (this.#child) {
-			// Remove event listeners but leave a fake 'error' hander to avoid
-			// propagation.
-			this.#child.removeAllListeners('exit');
-			this.#child.removeAllListeners('error');
-			this.#child.on('error', () => {});
-			this.#child.kill('SIGTERM');
-			this.#child = undefined;
-		}
+		this.#child.unref();
```
Comment (ibc) [inline node/src/Worker.ts]: I've randomly added this unref() call 😌

Comment (ibc) [reply node/src/Worker.ts]: And I've removed now since it is useless since we DO HAVE a IPC:

https://nodejs.org/api/child_process.html#subprocessunref

File: node/src/test/test-ActiveSpeakerObserver.ts (hunk 2 above)
Comment (jmillan) [inline node/src/test/test-ActiveSpeakerObserver.ts:33]: Maybe early return? 

```suggestion
	if (ctx.worker?.subprocessClosed) {
	    return;
	}
```

**Review by jmillan — APPROVED** [review]
Just added a cosmetic/style comment.

File: node/src/test/test-ActiveSpeakerObserver.ts (hunk 2 above)
Comment (nazar-pc) [reply node/src/test/test-ActiveSpeakerObserver.ts:33]: There is a comment above why `=== false` is necessary here

Comment (jmillan) [reply node/src/test/test-ActiveSpeakerObserver.ts:33]: > There is a comment above why === false is necessary here

I'm suggesting to early return if subprocess is closed so the following block (awaiting for it) is not indented. AFAIK we extensively use this pattern.

Comment (ibc) [reply node/src/test/test-ActiveSpeakerObserver.ts:33]: This is not appropriate here IMHO. This is not a method in which if some condition is false we don't want to do anything. See test-DirectTransport (or maybe test-PipeTransport) in which we create 2 workers so this early return fashion cannot be done because we have to do the same for both workers independently. This is not like checking the this.closed flag in a close() method. If I apply your suggestion and tomorrow we need to add more cleanup code in those afterEach() hooks then I would need to revert those changes  and leave the code as it is now in this PR.

Comment (ibc) [reply node/src/test/test-ActiveSpeakerObserver.ts:33]: Also your suggested code is wrong @jmillan. If the worker.subprocessClosed is not true it doesn't mean that we have to await for an event to happen in that worker, because as explained above the worker MAY NOT exist.

Comment (jmillan) [reply node/src/test/test-ActiveSpeakerObserver.ts:33]: Good
