### PR TITLE
Fix SIGSEGV at RTC::WebRtcTransport::OnIceServerTupleRemoved()

### LINKED ISSUE #883: SIGSEGV  at 'RTC::WebRtcTransport::OnIceServerTupleRemoved'
## Bug Report

It occurred  12 times in three days on ten servers.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000fffe19d71b4c in non-virtual thunk to RTC::WebRtcTransport::OnIceServerTupleRemoved(RTC::IceServer const*, RTC::TransportTuple*) () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
[Current thread is 1 (LWP 1882413)]
(gdb) 
(gdb) bt
#0  0x0000fffe19d71b4c in non-virtual thunk to RTC::WebRtcTransport::OnIceServerTupleRemoved(RTC::IceServer const*, RTC::TransportTuple*) () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#1  0x0000fffe19d71e68 in non-virtual thunk to RTC::WebRtcTransport::OnRtcTcpConnectionClosed(RTC::TcpServer*, RTC::TcpConnection*) () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#2  0x0000fffe1a1561c4 in TcpServerHandler::OnTcpConnectionClosed(TcpConnectionHandler*) () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#3  0x0000fffe19ea547c in uv.read () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#4  0x0000fffe19ea5b30 in uv.stream_io () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#5  0x0000fffe19eac7bc in uv.io_poll () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#6  0x0000fffe19e9faf4 in uv_run () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#7  0x0000fffe19ceb34c in DepLibUV::RunLoop() () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#8  0x0000fffe19cf4608 in Worker::Worker(Channel::ChannelSocket*, PayloadChannel::PayloadChannelSocket*) () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#9  0x0000fffe19ce9b88 in mediasoup_worker_run () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#10 0x0000fffe19b8c55c in std::sys_common::backtrace::__rust_begin_short_backtrace () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#11 0x0000fffe19bc5754 in core::ops::function::FnOnce::call_once{{vtable-shim}} () from /opt/ovice_ex_core/ovice_ex_core/lib/mediasoup_elixir-0.4.1/priv/native/libmediasoup_elixir.so
#12 0x0000fffe1a20f654 in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872
#13 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872
#14 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:108
#15 0x0000ffff9f2733f0 in ?? ()

```

### Your environment

- Operating system: Ubuntu 20.04.2
- Node version: N/A
- npm version: N/A
- gcc/clang version: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
- mediasoup version: Rust version mediasoup: 0.10.0 mediasoup-sys: 0.4.2
- mediasoup-client version: 3.6.50

### PR DESCRIPTION
**Pull request by ibc**
- Fixes #883

### Details

As @ybybwdwd said in in https://github.com/versatica/mediasoup/issues/883#issuecomment-1261976426:

- `IceServer` manages a list of `TransportTuples` instances in a `std::list`. Those are **not** pointers.
- When `IceServer` removes a tuple from the list (for different reasons), it removes it from its `std::list`, which means that the removed `TransportTuple` is **freed**. And then it notifies `WebRtcTransport` via `this->listener->OnIceServerTupleRemoved(this, removedTuple);`.
- Problem was that `WebRtcTransport` reads tuple data (`tuple->GetProtocol()` etc) within its `OnIceServerTupleRemoved()` method, so it's reading freed memory!, so crash.

Solution is to first notify the listener (`WebRtcTransport`) then remove it from the list (so free it after used).

### CODE REVIEW

File: worker/src/RTC/IceServer.cpp [hunk 1]
```diff
@@ -294,18 +296,27 @@ namespace RTC
...
 		{
 			this->selectedTuple = nullptr;
 
 			// Mark the first tuple as selected tuple (if any).
-			if (this->tuples.begin() != this->tuples.end())
+			// NOTE: The tuple being removed is still in the list.
+			if (this->tuples.size() >= 2)
 			{
-				SetSelectedTuple(std::addressof(*this->tuples.begin()));
+				for (auto it2 = this->tuples.begin(); it2 != this->tuples.end(); ++it2)
```
Comment (jmillan) [inline worker/src/RTC/IceServer.cpp]:
```suggestion
				for (const auto& tuple: this->tuples)
```

**Review by jmillan — APPROVED** [review]

**Comment by jmillan** [comment]
Apart from a range loop change suggestion, :+1:

**Review by jmillan — CHANGES_REQUESTED** [review]
@ibc,

I find this cleaner:

```patch
diff --git a/worker/src/RTC/IceServer.cpp b/worker/src/RTC/IceServer.cpp
index 27db36344..5962a4516 100644
--- a/worker/src/RTC/IceServer.cpp
+++ b/worker/src/RTC/IceServer.cpp
@@ -294,6 +294,8 @@ namespace RTC
                if (!removedTuple)
                        return;

+               // Notify the listener.
+               this->listener->OnIceServerTupleRemoved(this, removedTuple);
                // Remove it from the list of tuples.
                this->tuples.erase(it);

@@ -316,9 +318,6 @@ namespace RTC
                                this->listener->OnIceServerDisconnected(this);
                        }
                }
-
-               // Notify the listener.
-               this->listener->OnIceServerTupleRemoved(this, removedTuple);
        }

        void IceServer::ForceSelectedTuple(const RTC::TransportTuple* tuple)
```


We first notify the listener about the removed tuple, then tell it about the new selected one or about the disconnection. This flow seems more logical to me.

File: worker/src/RTC/IceServer.cpp (hunk 1 above)
Comment (ibc) [reply worker/src/RTC/IceServer.cpp]: on it

**Comment by ibc** [comment]
Agreed. Please @jmillan review again.

**Review by jmillan — APPROVED** [review]
👍
