### PR TITLE
RtpPacket: Make (almost) all methods remove payload padding if present

### LINKED ISSUE #1379: RtpPacket::SetPayloadLength get wrong payloadLength
Hi,
this method padding length to 4 bytes, however it change ```real payloadLength```  and remove padding flags , is that the correct ?
I thing we should check padding length is the same as orig length, if padding happen then set padding flag to true and set padding byte to padding length.

```
void RtpPacket::SetPayloadLength(size_t length)
	{
		MS_TRACE();

		// Pad desired length to 4 bytes.
		length = static_cast<size_t>(Utils::Byte::PadTo4Bytes(static_cast<uint16_t>(length)));

		this->size -= this->payloadLength;
		this->size -= size_t{ this->payloadPadding };
		this->payloadLength  = length;
		this->payloadPadding = 0u;
		this->size += length;

		SetPayloadPaddingFlag(false);
}
```

[https://github.com/versatica/mediasoup/blob/d6373d540751c06b7fb96f0e7e26ad56f50f25bd/worker/src/RTC/RtpPacket.cpp#L653](url)

### PR DESCRIPTION
**Pull request by ibc**
Fixes #1379

### Details

Before this PR:

- We have inconsistent behavior: some methods in `RtpPacket` keep existing payload padding after mangling the payload others don't.
- Those methods that keep existing payload do it wrong (real bug here) since they do NOT write the number of padding bytes in the last byte of the padding.

After this PR:

- All methods (but `clone()`) remove payload padding if present. Period.
- There is no real need to keep padding (AKA be padded to 4 bytes). That's just for super legazy plain RTP engines.
- "And why don't we keep existing padding instead?". See section above "Before this PR". Lot of work for little/null benefit. I don't want to waste much energy on this topic given that (when time comes in) I'd like to focus on task https://github.com/versatica/mediasoup/issues/1233 instead.

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

File: worker/src/RTC/RtpPacket.cpp [hunk 1]
```diff
@@ -650,20 +650,23 @@ namespace RTC
...
 		this->size -= this->payloadLength;
 		this->size -= size_t{ this->payloadPadding };
 		this->payloadLength  = length;
-		this->payloadPadding = 0u;
-		this->size += length;
+		this->payloadPadding = payloadPadding;
+		this->size += this->payloadLength + this->payloadPadding;
 
-		SetPayloadPaddingFlag(false);
+		SetPayloadPaddingFlag(this->payloadPadding > 0);
```
Comment (ibc) [inline worker/src/RTC/RtpPacket.cpp]: Oh this is not correct because we have to write number of padding bytes in the last byte of the padding right? I mean, SerPayloadPaddingFlag() doesn't do it AFAIR (I am out now).

**Review by jmillan — APPROVED** [review]
