### PR TITLE
`router.pipeToRouter()` can now connect two `Routers` in the same `Worker`

### LINKED ISSUE #1602: Critical router.pipeToRouter() error with Channel request handler
Hello Mediasoup Community,

I am experiencing a critical issue with `router.pipeToRouter()` that has persisted despite numerous attempts to resolve it.

**The Problem:**

I have a single Mediasoup Worker with two Routers. My goal is to pipe a video and audio stream from `Router 1` (Station Router) to `Router 2` (Manager Router). However, when the `pipeToRouter()` method is called for the video stream, it consistently fails with the following error:

`Error: Channel request handler with ID [original_producer_id] already exists [method:transport.produce]`

**What I Have Tried:**

- I am using `mediasoup@3.11.4` on the backend and `mediasoup-client@3.9.8` on the frontend. I've updated both to the latest versions, but the error remains.
- I've implemented a sequential, two-step piping process. The video pipe operation completes, and only then does a separate function attempt to pipe the audio stream.
- I've implemented a locking mechanism using a `Set` to prevent simultaneous `pipeToRouter()` calls.
- I've also tried a client-side approach where I only send the `start-piping` event to the server after both video and audio producers are successfully created.

**Context:**

- The error occurs specifically on the `pipeToRouter()` call, during the internal `transport.produce` method.
- The ID in the error message is the same as the original producer ID, suggesting that the method is attempting to create a new producer with a non-unique ID, which should not happen.

This issue seems to be a deep-rooted race condition or an internal bug within the `pipeToRouter` method itself.

Has anyone encountered this specific error before, or do you have any suggestions on how to work around this issue? Your help would be greatly appreciated.

Thank you.

### PR DESCRIPTION
**Pull request by ibc**
## Details

- Fixes #1602
- Remove the limitation by which `router1.pipeToRouter({ router: router2, etc })` throws if both `router1` and `router2` are in the same `Worker`.
- The solution is very simple: When we `produce()` the internally created `pipeConsumer` into the target `router`, pass a random `producerId` instead of keeping the same `id` that the original `producer` has.
- This may break some applications if they assume that the generated `pipeProducer` has same `id` than the `original` producer. The application should obtain the new `id` from the `{ pipeProducer, pipeDataProducer }` returned by `pipeToRouter()` method.
- **In order to avoid breaking existing applications that assume that the `pipeProducer.id` is the same as the original `producer.id`**, this new behavior is disabled by default. To enable it, `keepId: false` must be passed to `pipeToRouter()`.

## TODO

- [x] Document the new `keepId` field and new behavior in the docs.
- [x] Remove or clarify the note in the docs: https://mediasoup.org/documentation/v3/mediasoup/api/#router-pipeToRouter
- [x] Make public announcement.

### CODE REVIEW

File: node/src/Router.ts [hunk 1]
```diff
@@ -1088,7 +1088,8 @@ export class RouterImpl<RouterAppData extends AppData = AppData>
 				});
 
 				pipeProducer = await remotePipeTransport!.produce({
-					id: producer.id,
+					// Generate a new id for the pipeProducer.
+					id: utils.generateUUIDv4(),
```
Comment (nazar-pc) [inline node/src/Router.ts]: This will certainly break applications that used the feature in the past. I think there should be some other solution, like having an option to reuse producer ID or to generate a new one. I wrote such applications in the past myself.

Moreover, it is much harder to debug this way.

Comment (ibc) [reply node/src/Router.ts]: Yes, there should be another option, but I already spent tons of hours some months ago trying to figure out one and it doesn't exist. Current behavior in v3 is that `pipeToRouter()` generates pipe Producers with same `id` so the app doesn't check the generated `pipeProducer.id` and they assume they can safely `consume()` from the target router using the original `producer.id`. So no, there is no other solution.

Said that, I could add an option in `pipeToRouter()` to make this new behavior optional, but I will make it default to enabled.

Comment (ibc) [reply node/src/Router.ts]: Ok, I will make it disabled by default.

Comment (nazar-pc) [reply node/src/Router.ts]: There is an option to keep ID if router is different, but change if it is the same, but that would be confusing. I also didn't find a real need for this behavior to be completely honest.

Comment (ibc) [reply node/src/Router.ts]: There have been many many reports or complains or feature requests or questions about people that, for whatever reason, want to connect routers no matter they run in the same worker.

Comment (ibc) [reply node/src/Router.ts]: Ok, `keepId: boolean` (default `true`) added:

https://github.com/versatica/mediasoup/pull/1604/commits/2316ec4ec19cc90b9872ad3865b27aa5c4e6e438

File: rust/src/router.rs [hunk 2]
```diff
@@ -162,6 +170,12 @@ impl PipeToRouterOptions {
             enable_srtp: false,
         }
     }
+
+    /// Set `keep_id`.
+    pub fn with_keep_id(mut self, keep: bool) -> Self {
+        self.keep_id = keep;
+        self
+    }
```
Comment (nazar-pc) [inline rust/src/router.rs]: Not sure this method is needed. We didn't have other `.with_*` methods before.

File: rust/src/router.rs [hunk 3]
```diff
@@ -1083,7 +1097,9 @@ impl Router {
     ) -> Result<PipeProducerToRouterPair, PipeProducerToRouterError> {
         debug!("pipe_producer_to_router()");
 
-        if pipe_to_router_options.router.id() == self.id() {
+        let PipeToRouterOptions { keep_id, .. } = pipe_to_router_options;
+
+        if keep_id && pipe_to_router_options.router.id() == self.id() {
```
Comment (nazar-pc) [inline rust/src/router.rs]: This is inconsistent. Let's either do this:
```suggestion
        if pipe_to_router_options.keep_id && pipe_to_router_options.router.id() == self.id() {
```
Or if you want to make the line shorter then this:
```suggestion
        let PipeToRouterOptions { router, keep_id, .. } = &pipe_to_router_options;

        if *keep_id && router.id() == self.id() {
```

**Review by nazar-pc — COMMENTED** [review]
Overall makes sense, just some code style nits.

Note that this is a backwards compatible change for Rust because one of the fields of `PipeToRouterOptions` was already private.

File: rust/src/router.rs (hunk 2 above)
Comment (ibc) [reply rust/src/router.rs]: Then what do you propose?

Comment (nazar-pc) [reply rust/src/router.rs]: For this method - just remove it. You can change the field directly just like with any other.

File: rust/src/router.rs (hunk 3 above)
Comment (ibc) [reply rust/src/router.rs]: We **need** to extract `keep_id` **before** moving `pipe_to_router_options` to `self.get_or_create_pipe_transport_pair()` so your proposal doesn't compile.

File: rust/src/router.rs (hunk 2 above)
Comment (ibc) [reply rust/src/router.rs]: No, I can't XD.

Comment (ibc) [reply rust/src/router.rs]:
```rust
impl PipeToRouterOptions {
    /// Crate pipe options for piping into given local router.
    #[must_use]
    pub fn new(router: Router) -> Self {
```

Only `router` can be set when creating a `PipeToRouterOptions`.

And in the tests, for whatever reasons, this is done:

```rust
router1.pipe_producer_to_router(
  video_producer.id(),
    PipeToRouterOptions::new(router1bis.clone()),
  )
  .await;
```

Comment (nazar-pc) [reply rust/src/router.rs]: That is not true:
```rust
{
    let mut options = PipeToRouterOptions::new(router1bis.clone());
    options.keep_id = false;
    options
}
```

File: rust/src/router.rs (hunk 3 above)
Comment (nazar-pc) [reply rust/src/router.rs]: I don't understand what doesn't compile. Which option have you tried and what was the compiler error?

Comment (ibc) [reply rust/src/router.rs]: I've done it here: https://github.com/versatica/mediasoup/pull/1604/commits/d736b90ff67a7fbb45a13114fa80d48483c4b124

Comment (nazar-pc) [reply rust/src/router.rs]: I never liked `ref`, but sure, that works too.

File: rust/src/router.rs (hunk 2 above)
Comment (ibc) [reply rust/src/router.rs]: Oh, I didn't know that syntax... done here https://github.com/versatica/mediasoup/pull/1604/commits/5174cc1c98bea57e38079e92c98744df7d00f894

**Review by nazar-pc — APPROVED** [review]

File: rust/src/router.rs (hunk 2 above)
Comment (nazar-pc) [reply rust/src/router.rs]: It is just a variable and the fact that blocks are expressions

Comment (ibc) [reply rust/src/router.rs]: and the block doesn't not end with a explicit `return options` because just ending with `options` is more obvious (it's not).

**Comment by ibc** [comment]
Released in mediasoup 3.19.0
