### PR TITLE
Fix DTLS packets do not honor configured DTLS MTU (attempt 3)

### LINKED ISSUE #1100: DTLS fragment exceeds MTU size if the certificate is large.
Despite mediasoup setting the [DTLS MTU using SSL_set_mtu and DTLS_set_link_mtu](https://github.com/versatica/mediasoup/issues/4), if the certificate is large, the UDP packet may still exceed the MTU limit.

Reproduce the bug by:

```bash
git clone https://github.com/winlinvip/mediasoup-demo.git &&
cd mediasoup-demo && git checkout bug/dtls-for-large-cert
```

> Note: We modify the server.js to support DTLS certificate, see https://github.com/winlinvip/mediasoup-demo/commit/5b6e87514ff1a7ad307184a5bc2a894b61944f34

Generate a large certificate:

```bash
mkdir -p server/certs &&
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 \
    -keyout server/certs/privkey.pem -out server/certs/fullchain.pem
```

> Note: Just for the purpose of reproducing the issue, a 4096-bit certificate was used. Even if you use a 1024-bit certificate, you can still add a lot of additional information.

Run server:

```bash
cd server
npm install && cp config.example.js config.js
npm start
```

Run app:

```bash
cd app
npm install --legacy-peer-deps
npm start
```

The number 4 packet in the below picture shows that the DTLS packet is 2008 bytes, which exceeds the UDP MTU.

image

[mediasoup-large-cert.pcapng.zip](https://github.com/versatica/mediasoup/files/11632664/mediasoup-large-cert.pcapng.zip)

### PR DESCRIPTION
**Pull request by ibc**
- Fixes #1100
- Based on PR #1156 which was based on PR #1143

### Details

This PR is the same as PR #1156. However that PR introduced a memory leak (see issue #1340). This PR fixes that leak by following the discussion and research in associated issues and PRs, specially here: https://github.com/versatica/mediasoup/issues/1340#issuecomment-1965375082

To prove that this PR works at DTLS level, here the DTLS messages sent from mediasoup to browser while doing the DTLS handshake:

```
RTC::DtlsTransport::SendDtlsData() | 1349 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 1349 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 1349 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 1349 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 1349 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 242 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 67 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 129 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 385 bytes of DTLS data ready to be sent
RTC::DtlsTransport::SendDtlsData() | 45 bytes of DTLS data ready to be sent
```

which clearly corresponds to what we see in Wireshark (there is a huge certificate so it's splitted into N DTLS Certificate fragments):

CleanShot-2024-02-27-at-16 51 19@2x

Note that sizes of each message match the DTLS data sent by mediasoup plus UDP and IP encapsulation (32 bytes always).

### CODE REVIEW

**Comment by ibc** [comment]
CC @gkrol-katmai @pnts-se

File: worker/src/RTC/DtlsTransport.cpp [hunk 1]
```diff
@@ -708,15 +734,19 @@ namespace RTC
...
-		// TODO: This is not honored, see issue:
-		//   https://github.com/versatica/mediasoup/issues/1100
 		SSL_set_mtu(this->ssl, DtlsMtu);
 		DTLS_set_link_mtu(this->ssl, DtlsMtu);
 
+		// We want to monitor OpenSSL write operations into our |sslBioToNetwork|
+		// buffer so we can immediately send those DTLS bytes (containing full DTLS
+		// messages, or valid DTLS fragment messages, or combination of them) to
+		// the endpoint, and hence we honor the configured DTLS MTU.
+		BIO_set_callback_ex(this->sslBioToNetwork, onSslBioOut);
```
Comment (jmillan) [inline worker/src/RTC/DtlsTransport.cpp:754]: wasn't this an experimental function used to debug?

https://www.openssl.org/docs/man3.2/man3/BIO_set_callback_ex.html

File: worker/src/RTC/DtlsTransport.cpp [hunk 2]
```diff
@@ -1022,9 +1047,24 @@ namespace RTC
...
+
+		MS_DEBUG_DEV("%zu bytes of DTLS data ready to be sent", len);
 
-		// Send data.
-		SendPendingOutgoingDtlsData();
+		// Notify the listener.
+		this->listener->OnDtlsTransportSendData(this, data, len);
+
+		// Clear the BIO buffer.
+		// NOTE: Here we now that OpenSSL called the onSslBioOut() callback with
```
Comment (jmillan) [inline worker/src/RTC/DtlsTransport.cpp]:
```suggestion
		// NOTE: Here we now that OpenSSL called the onSslBioOut() callback
```

File: worker/src/RTC/DtlsTransport.cpp [hunk 3]
```diff
@@ -1022,9 +1047,24 @@ namespace RTC
...
+		// with all the byte length that it previously wrote into the BIO mem
+		// buffer (this->sslBioToNetwork), so it's safe to clear the entire buffer
+		// after sending its entire DTLS data to the endpoint.
+		// NOTE: the (void) avoids the -Wunused-value warning.
+		(void)BIO_reset(this->sslBioToNetwork);
```
Comment (jmillan) [inline worker/src/RTC/DtlsTransport.cpp]: `BIO_reset()` returns -1 on failure. It would be nice to log it in case of error.

File: worker/src/RTC/DtlsTransport.cpp [hunk 4]
```diff
@@ -47,15 +47,41 @@ inline static void onSslInfo(const SSL* ssl, int where, int ret)
...
+  int ret,
+  size_t* /*processed*/)
+{
+	long resultOfcallback = (operationType == BIO_CB_RETURN) ? static_cast<long>(ret) : 1;
+
+	// This callback is called twice for write operations:
+	// - First one with operationType = BIO_CB_WRITE.
+	// - Second one with operationType = BIO_CB_RETURN | BIO_CB_WRITE.
+	// We only care about the former.
+	if (operationType == BIO_CB_WRITE && argp && len > 0)
```
Comment (jmillan) [inline worker/src/RTC/DtlsTransport.cpp]: Cosmetic for readability:

```suggestion
	if ((operationType == BIO_CB_WRITE) && argp && len > 0)
```

**Review by jmillan — APPROVED** [review]
:+1: :+1:

File: worker/src/RTC/DtlsTransport.cpp (hunk 2 above)
Comment (ibc) [reply worker/src/RTC/DtlsTransport.cpp:1062]: No.

> `BIO_set_callback_ex()` and `BIO_get_callback_ex()` set and retrieve the BIO callback. The callback is called during most high-level BIO operations. It can be used for debugging purposes to trace operations on a BIO or **to modify its operation**.

File: worker/src/RTC/DtlsTransport.cpp (hunk 1 above)
Comment (ibc) [reply worker/src/RTC/DtlsTransport.cpp:754]: No.

> `BIO_set_callback_ex()` and `BIO_get_callback_ex()` set and retrieve the BIO callback. The callback is called during most high-level BIO operations. It can be used for debugging purposes to trace operations on a BIO or **to modify its operation**.

File: worker/src/RTC/DtlsTransport.cpp (hunk 2 above)
Comment (ibc) [reply worker/src/RTC/DtlsTransport.cpp]: Fixed in local branch.

File: worker/src/RTC/DtlsTransport.cpp (hunk 3 above)
Comment (ibc) [reply worker/src/RTC/DtlsTransport.cpp]: It must return 1 on success on our BIO. Pushed.

File: worker/src/RTC/DtlsTransport.cpp (hunk 4 above)
Comment (ibc) [reply worker/src/RTC/DtlsTransport.cpp]: Pushed.

**Comment by gkrol-katmai** [comment]
The code looks good to me! I think we now have a good grasp of what's going on. I know that adding the 'reset' in that function will fix the leak. I haven't tested this PR.

Not sure what the coding standards are for comments, but I would suggest we add comments to onSslBioOut and DtlsTransport::SendDtlsData (above the implementation). Those should describe the effect of the function and when/why it gets called. Preferably `/** */` style. We're doing some subtle things here so we need to be extra clear.

**Comment by ibc** [comment]
> I know that adding the 'reset' in that function will fix the leak. I haven't tested this PR.

I think this is also proven here https://github.com/versatica/mediasoup/issues/1340#issuecomment-1966393672 where it's clear that the `onSslBioOut` is always called with `len` matching the previous `mem_write()` call.

> Not sure what the coding standards are for comments, but I would suggest we add comments to `onSslBioOut` and `DtlsTransport::SendDtlsData` (above the implementation). Those should describe the effect of the function and when/why it gets called. Preferably `/** */` style. We're doing some subtle things here so we need to be extra clear.

Done here: https://github.com/versatica/mediasoup/pull/1345/commits/e827248427956f53c442ae1a930700f213d9edb4

**Comment by ibc** [comment]
BTW I've added some logs and Wireshark capture in the PR description above proving that everything makes sense.

**Comment by ibc** [comment]
Let's merge and release. Thanks a lot.
