### PR TITLE
Fix issue 932

### LINKED ISSUE #932: Worker crash due to std::out_of_range exception
## Bug Report

mediasoup worker crashed in the demo site (v3demo.mediasoup.org) running latest 3.10.11.

### Your environment

- Operating system: Linux Debian
- Node version: v16.13.1
- gcc/clang version: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- mediasoup version: 3.10.11

### Issue description

No idea where this happened:

```
2022-10-26T07:22:05.449Z mediasoup:ERROR:Worker (stderr) terminate called after throwing an instance of '
2022-10-26T07:22:05.449Z mediasoup:ERROR:Worker (stderr) std::out_of_range
2022-10-26T07:22:05.449Z mediasoup:ERROR:Worker (stderr) '
2022-10-26T07:22:05.450Z mediasoup:ERROR:Worker (stderr)   what():  
2022-10-26T07:22:05.450Z mediasoup:ERROR:Worker (stderr) vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 2)
2022-10-26T07:22:05.452Z mediasoup:ERROR:Worker worker process died unexpectedly [pid:18091, code:null, signal:SIGABRT]
```

### PR DESCRIPTION
**Pull request by ibc**
Hopefully fixes #932

We've been looking for all calls to `.at()` and other calls that may produce `std::out_of_range` as explained in https://github.com/versatica/mediasoup/issues/932#issuecomment-1292176319.

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

**Review by jmillan — APPROVED** [review]

File: worker/src/RTC/SimulcastConsumer.cpp [hunk 1]
```diff
@@ -627,7 +627,7 @@ namespace RTC
 		auto nowMs = DepLibUV::GetTimeMs();
 		uint32_t desiredBitrate{ 0u };
 
-		for (size_t sIdx{ this->producerRtpStreams.size() - 1 }; sIdx >= 0; --sIdx)
+		for (int16_t sIdx{ static_cast<int16_t>(this->producerRtpStreams.size() - 1) }; sIdx >= 0; --sIdx)
```
Comment (jmillan) [inline worker/src/RTC/SimulcastConsumer.cpp]:
```suggestion
		for (auto sIdx{ static_cast<int16_t>(this->producerRtpStreams.size() - 1) }; sIdx >= 0; --sIdx)
```

Comment (ibc) [reply worker/src/RTC/SimulcastConsumer.cpp]: done

**Review by jmillan — APPROVED** [review]
