### PR TITLE
SeqManager: Properly remove dropped entries

### LINKED ISSUE #1037: High packet loss after upgrading to 3.11.16 version
## Bug Report
After upgrading to the last release (containing https://github.com/versatica/mediasoup/pull/1032), when running with limited networking I got a lot of warnings like these:

```
mediasoup:WARN:Channel [pid:1032678] RTC::RtpRetransmissionBuffer::Insert() | packet timestamp is higher than timestamp of immediate newer packet in the buffer, discarding it [ssrc:138048629, seq:14606, timestamp:2513086702] +52ms
RTC::RtpRetransmissionBuffer::Dump() | <RtpRetransmissionBuffer>
RTC::RtpRetransmissionBuffer::Dump() |   buffer [size:205, maxSize:5000]
RTC::RtpRetransmissionBuffer::Dump() |   oldest item [seq:14466, timestamp:2512420792]
RTC::RtpRetransmissionBuffer::Dump() |   newest item [seq:14670, timestamp:2512600792]
RTC::RtpRetransmissionBuffer::Dump() |   buffer window: 4294921574ms
RTC::RtpRetransmissionBuffer::Dump() | </RtpRetransmissionBuffer>
```

```
mediasoup:WARN:Channel [pid:1032678] RTC::RtpRetransmissionBuffer::Insert() | packet has less seq but higher timestamp than oldest packet in the buffer, discarding it [ssrc:409260887, seq:18365, timestamp:1026593387] +44ms
RTC::RtpRetransmissionBuffer::Dump() | <RtpRetransmissionBuffer>
RTC::RtpRetransmissionBuffer::Dump() |   buffer [size:165, maxSize:5000]
RTC::RtpRetransmissionBuffer::Dump() |   oldest item [seq:24816, timestamp:1024930187]
RTC::RtpRetransmissionBuffer::Dump() |   newest item [seq:24980, timestamp:1025106407]
RTC::RtpRetransmissionBuffer::Dump() |   buffer window: 1958ms
RTC::RtpRetransmissionBuffer::Dump() | </RtpRetransmissionBuffer>
```

Reading the last log I see that:
- the buffer state is: oldest item [seq:24816, timestamp:1024930187], newest item [seq:24980, timestamp:1025106407]
- new packet with seq:18365, timestamp:1026593387 is dropped
- seq:18365 probably belongs to a newer packet counted at the next cycle, so it should became the newest item in the buffer

### PR DESCRIPTION
**Pull request by jmillan**
Fixes #1037.

Keep dropped entries clean by removing those higher than this->maxInput.

This cleans both the `Insert()` and `ClearDropped()` methods. We remove those dropped entries which are from a previous sequence iteration.

STR with mediasoup-demo with single host:

Tab 1: roomId=loss&forceVP9=true&consume=false
Tab 2: roomId=loss&forceVP9=true&produce=false

In tab 2, select the preferred layers (0,0). Many packets are discarded by the codec

It takes few minutes until the seq number wraps ups. Wait for 1 or two wraps up. Vide in Tab 2 should be OK.

### CODE REVIEW

**Comment by jmillan** [comment]
@vpalmisano I've tested this with the STR that I provided and which is failing in V3. Can you give it a try?

**Comment by ibc** [comment]
I must confess that I don't understand whether the PR description describes an issue or the working solution.

**Comment by vpalmisano** [comment]
> Can you give it a try?

After 1h test I got no big loss events, so probably we could say that this was fixed :)

**Comment by jmillan** [comment]
Test failing.. I was filtering by [SeqManager] in local..., checking..

**Comment by jmillan** [comment]
There are some changes in the tests generated out of the Fuzzer output. I've reviewed them and they make sense.

File: worker/src/RTC/SeqManager.cpp [hunk 1]
```diff
@@ -70,6 +71,14 @@ namespace RTC
 		// There are dropped inputs. Synchronize.
 		if (!this->dropped.empty())
 		{
+			// Set maxInput here if needed before calling ClearDropped.
```
Comment (ibc) [inline worker/src/RTC/SeqManager.cpp]:
```suggestion
			// Set maxInput here if needed before calling ClearDropped().
```

**Review by ibc — APPROVED** [review]

**Comment by jmillan** [comment]
@ibc, no hurries. Reassigning for review since I've done some performance improvements. IMHO `Input()` method is now even more clear and understandable:

1: No need to consider dropped inputs if `this->dropped` is empty.
2: If 'input'  is higher than `this->maxInput` then reassign `this->maxInput` and clean dropped inputs accordingly.
3: No need to consider dropped inputs if `this->dropped` is empty after cleanup.
4: Nothing to do if 'input' is within `this->dropped`.
5: Calculate new `base` if there are dropped inputs lower than 'input'.

**Review by ibc — APPROVED** [review]
LGTM. Is it fuzzer safe?

**Comment by jmillan** [comment]
> LGTM. Is it fuzzer safe?

I didn't try honestly. let me try it tomorrow morning.

**Comment by jmillan** [comment]
>> LGTM. Is it fuzzer safe?

> I didn't try honestly. let me try it tomorrow morning.

We are safe.
