### PR TITLE
`Consumer` classes: Really fix target layer retransmission buffer

### LINKED ISSUE #1554: Worker crash: 'std::out_of_range' in `absl::container_internal::raw_hash_map<>::at undefined`
# Bug Report

## Your environment

- Operating system: Linux Debian
- gcc/clang version: gcc 12.2.0 (Debian 12.2.0-14)
- mediasoup version: 3.16.1

## Issue description

mediasoup-demo crashes with this error:

```
2025-06-26T14:35:13.386Z mediasoup:ERROR:Worker (stderr) terminate called after throwing an instance of 'std::out_of_range' undefined
2025-06-26T14:35:13.388Z mediasoup:ERROR:Worker (stderr)   what():  absl::container_internal::raw_hash_map<>::at undefined
2025-06-26T14:35:13.419Z mediasoup:ERROR:Channel Producer Channel error: Error: read ECONNRESET undefined
2025-06-26T14:35:13.439Z mediasoup:ERROR:Worker worker process died unexpectedly [pid:3452214, code:null, signal:SIGABRT] undefined
```

Also reported in the forum: https://mediasoup.discourse.group/t/mediasoup-worker-unexpectedly-died-in-v3-16-1/6741

### Core dump

```
(gdb) bt full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140720918794352}}
        ret = <optimized out>
#1  0x00007f2462dcad9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
No locals.
#2  0x00007f2462d7bf32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007f2462d66472 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {18446744073709551615, 13835058058503389184, 13835058058503389184, 18446744073709551615, 
              18446603336221196287, 13835058058503389184, 13835058058503389184, 93978900237968, 1152518615, 25353, 139794254143209, 139794255525504, 139794254144243, 139794255525504, 10, 
              139794253604032}}, sa_flags = 1658574970, sa_restorer = 0x55792b348e78}
#4  0x00007f246309d919 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007f24630a8e1a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007f24630a8e85 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007f24630a90d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x0000557928cccc39 in absl::lts_20240722::base_internal::ThrowStdOutOfRange(char const*) ()
No symbol table info available.
#9  0x0000557928df22fb in RTC::SimulcastConsumer::SendRtpPacket(RTC::RtpPacket*, std::shared_ptr<RTC::RtpPacket>&) ()
No symbol table info available.
#10 0x0000557928df2924 in RTC::SimulcastConsumer::SendRtpPacket(RTC::RtpPacket*, std::shared_ptr<RTC::RtpPacket>&) ()
No symbol table info available.
#11 0x0000557928da0362 in RTC::Router::OnTransportProducerRtpPacketReceived(RTC::Transport*, RTC::Producer*, RTC::RtpPacket*) ()
No symbol table info available.
#12 0x0000557928d8b2db in RTC::Producer::ReceiveRtpPacket(RTC::RtpPacket*) ()
No symbol table info available.
#13 0x0000557928e05651 in RTC::Transport::ReceiveRtpPacket(RTC::RtpPacket*) ()
No symbol table info available.
#14 0x0000557928e2fefe in RTC::WebRtcTransport::OnRtpDataReceived(RTC::TransportTuple*, unsigned char const*, unsigned long) ()
No symbol table info available.
#15 0x0000557928e25a02 in RTC::WebRtcServer::OnUdpSocketPacketReceived(RTC::UdpSocket*, unsigned char const*, unsigned long, sockaddr const*) ()
No symbol table info available.
#16 0x000055792914ac4d in uv.udp_recvmmsg ()
```

### PR DESCRIPTION
**Pull request by ibc**
Fixes #1554.

## Details

- Use a new `SharedRtpPacket` instead of passing a `shared_ptr<RtpPacket>`.
- Make `RtpStreamSend::ReceivePacket(packet, sharedPacket)` return a result telling whether the packet was discarded, accepted but not stored or accepted + stored.
- `Consumer` classes: After passing the **mangled** packet to `rtpStreamSend->ReceivePacket(packet, sharedPacket)`, if result is that the packet was stored, then fill `sharedPacket` if it was empty.

### CODE REVIEW

**Comment by ibc** [comment]
## I've found the problem

In `RtpTransmissionBuffer::FillItem(packet, sharedPacket)`, if `sharedPacket` is empty, we clone the given `packet` into it.

The problem is that the given `packet` has been previously modified by `Consumer::SendRtpPacket()` before it passes it to `this->rtpStream->ReceivePacket(packet, sharedPacket)` (which is the one that ends calling to `rtpRetransmissionBuffer->Insert(packet, sharedPacket)`.

Here the problem is that, indeed, we need that this->rtpStream->ReceivePacket(packet, sharedPacket)` receives the packet modified by the Consumer. `Consumer::SendRtpPacket()` restores the **original** packet later, but of course those changes don't affect the cloned packet in `sharedPacket`.

**A solution could be the following:**

In `Consumer::SendRtpPacket()` we not only restore the `packet` but also the cloned packet in the `sharedPacket` (if it has value).

I've applied that fix in `SimulcastConsumer` in this branch in this commit: https://github.com/versatica/mediasoup/pull/1558/commits/082d234ced84a4a3b57af473e758da4ef80864a1

**Review by jmillan — DISMISSED** [review]

**Comment by ibc** [comment]
## TODO 1 (in theory solved)

When generating packet loss and uplink limitation etc, eventually a crash happens:

```
mediasoup:ERROR:Worker (stderr) (ABORT) RTC::RtpStreamSend::ReceiveNack() | failed assertion `item->sharedPacket.HasPacket()': item doesn't contain a packet [ssrc:117574087, seq:23278, timestamp:690523278]
```

The issue happens in `RtpStreamSend::ReceiveNack()` due to an assertion that I have added, but if such an assertion wouldn't exist then it would crash anyway:

```c++
FillRetransmissionContainer(item->GetPacketId(), item->GetLostPacketBitmask());

for (auto* item : RetransmissionContainer)
{
	if (!item)
	{
		break;
	}

	MS_ASSERT(
	  item->sharedPacket.HasPacket(),
	  "item doesn't contain a packet [ssrc:%" PRIu32 ", seq:%" PRIu16
	  ", timestamp:%" PRIu32 "]",
	  item->ssrc,
	  item->sequenceNumber,
	  item->timestamp);

	auto* packet = item->sharedPacket.GetPacket();

	// Keep the values of the original packet received by the Consumer.
	auto origSsrc      = packet->GetSsrc();
	auto origSeq       = packet->GetSequenceNumber();
	auto origTimestamp = packet->GetTimestamp();

```

It means that one of the items in the `RetransmissionContainer` has a `sharedPacket` member that does **NOT** have a `packet` inside.

This can only happen if **somewhere else** something called `sharedPacket.Reset()` in a copy of the same `SharedRtpPacket`.

## Brainstorming

Ok, for me this makes lot of sense. I mean, we are (and we were before all these changes) calling `this->sharedPacket.reset()` in `RtpRetransmissionBuffer::Item::Reset()`. 

However, now we do this:

```c++
this->sharedPacket.Reset();
```

This is the `SharedRtpPacket::Reset()` method which literally removes the internal packet from **ALL** the copies of the same `SharedRtpPacket` object. This is because `SharedRtpPacket` contains a `shared_ptr` that contains an `unique_ptr`, etc. So this is on purpose. But of course we cannot call this `SharedRtpPacket::Reset()` method within `RtpRetransmissionBuffer::Item::Reset()` because we are **literally** affecting items in the `this->buffer` of **other instances** of `RtpRetransmissionBuffer` (that belong to other `Consumers`).

## Solution

So the solution is this:

Within `RtpRetransmissionBuffer::Item::Reset()`:

```diff
- this->sharedPacket.Reset();
+ this->sharedPacket   = RTC::SharedRtpPacket();
```

**Comment by ibc** [comment]
This is ready for review. I cannot reproduce any crash anymore doing throttling stuff in the demo in local. I've also pushed this branch to the mediasoup-demo.

**Comment by ibc** [comment]
## TODO 2 (fixed)

In Linux, `make clean && make test-asan-address` fails:

```
=================================================================
==10816==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xffffb036302c at pc 0xaaaad6861fb0 bp 0xffffc3c26e00 sp 0xffffc3c265f0
READ of size 64 at 0xffffb036302c thread T0
    #0 0xaaaad6861fac in __asan_memcpy (/mediasoup/worker/out/Release/build/mediasoup-worker-test-asan-address+0x3b1fac) (BuildId: 8743122ce61ef973d670d3004094b3577606c73e)
    #1 0xaaaad6b234f4 in RTC::RtpPacket::Clone() const /mediasoup/worker/out/Release/build/../../../src/RTC/RtpPacket.cpp:741:4
    #2 0xaaaad6b99004 in RTC::SharedRtpPacket::Assign(RTC::RtpPacket const*) /mediasoup/worker/out/Release/build/../../../src/RTC/SharedRtpPacket.cpp:62:35
    #3 0xaaaad6f3f6a8 in CATCH2_INTERNAL_TEST_0() /mediasoup/worker/out/Release/build/../../../test/src/RTC/TestSimpleConsumer.cpp:267:16
    #4 0xaaaad7db406c in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) (/mediasoup/worker/out/Release/build/mediasoup-worker-test-asan-address+0x190406c) (BuildId: 8743122ce61ef973d670d3004094b3577606c73e)
    #5 0xaaaad7db331c in Catch::RunContext::runTest(Catch::TestCaseHandle const&) (/mediasoup/worker/out/Release/build/mediasoup-worker-test-asan-address+0x190331c) (BuildId: 8743122ce61ef973d670d3004094b3577606c73e)
    #6 0xaaaad7dd4680 in Catch::(anonymous namespace)::TestGroup::execute() catch_session.cpp
    #7 0xaaaad7dd3174 in Catch::Session::runInternal() (/mediasoup/worker/out/Release/build/mediasoup-worker-test-asan-address+0x1923174) (BuildId: 8743122ce61ef973d670d3004094b3577606c73e)
    #8 0xaaaad7dd23f8 in Catch::Session::run() (/mediasoup/worker/out/Release/build/mediasoup-worker-test-asan-address+0x19223f8) (BuildId: 8743122ce61ef973d670d3004094b3577606c73e)
    #9 0xaaaad6e6a2f4 in int Catch::Session::run<char>(int, char const* const*) /mediasoup/worker/out/Release/build/../../../subprojects/Catch2-3.6.0/src/catch2/catch_session.hpp:41:30
    #10 0xaaaad6e69df8 in main /mediasoup/worker/out/Release/build/../../../test/src/tests.cpp:55:23
    #11 0xffffb1e684c0 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #12 0xffffb1e68594 in __libc_start_main csu/../csu/libc-start.c:360:3
    #13 0xaaaad67c572c in _start (/mediasoup/worker/out/Release/build/mediasoup-worker-test-asan-address+0x31572c) (BuildId: 8743122ce61ef973d670d3004094b3577606c73e)

Address 0xffffb036302c is located in stack of thread T0 at offset 44 in frame
    #0 0xaaaad6f3df54 in CATCH2_INTERNAL_TEST_0() /mediasoup/worker/out/Release/build/../../../test/src/RTC/TestSimpleConsumer.cpp:156

  This frame has 41 object(s):
    [32, 44) 'buffer' (line 158)
    [64, 160) 'ref.tmp' (line 166) <== Memory access at offset 44 partially underflows this variable
    [192, 208) 'ref.tmp1' (line 166)
    [224, 240) 'agg.tmp'
    [256, 264) 'listener' (line 168)
    [288, 296) 'consumer' (line 169)
    [320, 328) 'rtpStream' (line 170)
    [352, 376) 'scores' (line 173)
    [416, 417) 'ref.tmp10' (line 173)
    [432, 433) 'ref.tmp11' (line 173)
    [448, 464) 'sharedPacket' (line 179)
    [480, 576) 'ref.tmp46' (line 189)
    [608, 624) 'ref.tmp47' (line 189)
    [640, 656) 'agg.tmp48'
    [672, 680) 'listener53' (line 191)
    [704, 712) 'consumer56' (line 192)
    [736, 744) 'rtpStream63' (line 197)
    [768, 792) 'scores66' (line 200)
    [832, 833) 'ref.tmp68' (line 200)
    [848, 849) 'ref.tmp73' (line 200)
    [864, 880) 'sharedPacket92' (line 206)
    [896, 992) 'ref.tmp119' (line 216)
    [1024, 1040) 'ref.tmp120' (line 216)
    [1056, 1072) 'agg.tmp121'
    [1088, 1096) 'listener126' (line 218)
    [1120, 1128) 'consumer129' (line 219)
    [1152, 1160) 'rtpStream136' (line 224)
    [1184, 1208) 'scores139' (line 227)
    [1248, 1249) 'ref.tmp141' (line 227)
    [1264, 1265) 'ref.tmp146' (line 227)
    [1280, 1296) 'sharedPacket165' (line 233)
    [1312, 1408) 'ref.tmp192' (line 243)
    [1440, 1456) 'ref.tmp193' (line 243)
    [1472, 1488) 'agg.tmp194'
    [1504, 1512) 'listener199' (line 245)
    [1536, 1544) 'consumer202' (line 246)
    [1568, 1576) 'rtpStream209' (line 251)
    [1600, 1624) 'scores212' (line 254)
    [1664, 1665) 'ref.tmp214' (line 254)
    [1680, 1681) 'ref.tmp219' (line 254)
    [1696, 1712) 'sharedPacket238' (line 260)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/mediasoup/worker/out/Release/build/mediasoup-worker-test-asan-address+0x3b1fac) (BuildId: 8743122ce61ef973d670d3004094b3577606c73e) in __asan_memcpy
Shadow bytes around the buggy address:
  0xffffb0362d80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0xffffb0362e00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0xffffb0362e80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0xffffb0362f00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0xffffb0362f80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0xffffb0363000: f1 f1 f1 f1 00[04]f2 f2 f8 f8 f8 f8 f8 f8 f8 f8
  0xffffb0363080: f8 f8 f8 f8 f2 f2 f2 f2 f8 f8 f2 f2 00 00 f2 f2
  0xffffb0363100: f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f8 f8 f2
  0xffffb0363180: f2 f2 f2 f2 f8 f2 f8 f2 f8 f8 f2 f2 f8 f8 f8 f8
  0xffffb0363200: f8 f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f8 f8 f2 f2
  0xffffb0363280: 00 00 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10816==ABORTING
make: *** [Makefile:102: test-asan-address] Error 1
```

## Explanation

Ok, the test was already wrong. Problem in `TestSimpleConsumer.cpp` is that we have this buffer:

```c++
uint8_t buffer[] =
{
	0x80, 0x01, 0x00, 0x08,
	0x00, 0x00, 0x00, 0x04,
	0x00, 0x00, 0x00, 0x05
};
```

We create a packet by parsing it:

```c++
auto* packet = RtpPacket::Parse(buffer, sizeof(buffer));
```

Such a packet has 12 bytes and has 0 payload length (verified by dumping it).

But later the test does things like this:

```c++
packet->SetPayloadLength(20);
```

And then, due to required changes in this PR, we have to keep the `sharedPacket` in sync with the changes in `packet` so I'm calling `sharedPacket.Assign(packet)`. The problem? By design (and this is ok) such a `Assign(packet)` method clones the given packet. And `Clone()` reads NON allocated memory since the `buffer` was only 12 bytes long.

## Solution

In this commit: https://github.com/versatica/mediasoup/pull/1558/commits/d8881cb05f5ca2485acef02c90d8955cfd5aafe1

File: worker/src/RTC/PipeConsumer.cpp [hunk 1]
```diff
@@ -361,9 +383,10 @@ namespace RTC
 			  origSeq);
 		}
 
-		const bool sent = rtpStream->ReceivePacket(packet, sharedPacket);
+		const RTC::RtpStreamSend::ReceivePacketResult result =
+		  rtpStream->ReceivePacket(packet, sharedPacket);
 
-		if (sent)
+		if (result > RTC::RtpStreamSend::ReceivePacketResult::DISCARDED)
```
Comment (jmillan) [inline worker/src/RTC/PipeConsumer.cpp]: `>` ? Can we use `==` or `!=` instead for readability? We don't need Consumers to know how `ReceivePacketResult` is internally stored. But basically for readability.

File: worker/src/RTC/SimulcastConsumer.cpp [hunk 2]
```diff
@@ -728,15 +728,39 @@ namespace RTC
...
 	{
 		MS_TRACE();
 
 #ifdef MS_RTC_LOGGER_RTP
 		packet->logger.consumerId = this->id;
 #endif
 
+		// Assert that, if sharedPacket has a packet inside, it's the same as the
+		// raw packet.
+		if (sharedPacket.HasPacket())
```
Comment (jmillan) [inline worker/src/RTC/SimulcastConsumer.cpp]: We could do this check in `Router` rather than here, so the check is done only in one place.

**Review by jmillan — APPROVED** [review]
Just few comments left.

File: worker/src/RTC/PipeConsumer.cpp (hunk 1 above)
Comment (ibc) [reply worker/src/RTC/PipeConsumer.cpp]: Will do

File: worker/src/RTC/SimulcastConsumer.cpp (hunk 2 above)
Comment (ibc) [reply worker/src/RTC/SimulcastConsumer.cpp]: Will do

File: worker/src/RTC/PipeConsumer.cpp (hunk 1 above)
Comment (ibc) [reply worker/src/RTC/PipeConsumer.cpp]: Done here: https://github.com/versatica/mediasoup/pull/1558/commits/7f9575cbdf420c36e80910df9dd207129ab49cfd

File: worker/src/RTC/SimulcastConsumer.cpp (hunk 2 above)
Comment (ibc) [reply worker/src/RTC/SimulcastConsumer.cpp]: Done here: https://github.com/versatica/mediasoup/pull/1558/commits/7f9575cbdf420c36e80910df9dd207129ab49cfd

**Comment by ibc** [comment]
This branch has been working in mediasoup-demo official app for 4 days and I've also tested it extensively locally with network throttle setup. No crashes. Merging.
