### PR TITLE
Rust: fix PipeConsumer get_stats()

### LINKED ISSUE #1510: Panic at consumer.rs:getStats() when cascade simulcast h264 stream
## Bug Report

**IMPORTANT:** We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in mediasoup.

If you have questions or doubts about mediasoup or need support, please use the mediasoup Discourse Group instead:

https://mediasoup.discourse.group

If you got a crash in mediasoup, please try to provide a core dump into the issue report:

https://mediasoup.org/support/#crashes-in-mediasoup-get-a-core-dump

### Your environment

- Operating system: Centos7.9
- Node version:
- npm version:
- gcc/clang version:
- mediasoup version: rust-0.17.1
- mediasoup-client version:

### Issue description

When publishing a Simulcast media stream using H.264, multiple RTP streams exist. When using a PipeTransport to send the stream to another mediasoup server, calling consumer::getStats returns two SendStats. However, when encountering the following code:

```
let consumer_stat = ConsumerStat::from_fbs(&data.stats[0]);
let producer_stat = ProducerStat::from_fbs(&data.stats[1]);

```
a panic occurs with the error: RecvStats data: SendStats.

### PR DESCRIPTION
**Pull request by jmillan**
Fixes #1510

Consider PipeConsumer which stats contains multiple send streams.

### CODE REVIEW

File: rust/src/router/consumer.rs [hunk 1]
```diff
@@ -442,6 +444,7 @@ impl ConsumerStats {
         match self {
             ConsumerStats::JustConsumer((consumer_stat,)) => consumer_stat,
             ConsumerStats::WithProducer((consumer_stat, _)) => consumer_stat,
+            ConsumerStats::MultipleConsumers(consumer_stats) => &consumer_stats[0],
```
Comment (jmillan) [inline rust/src/router/consumer.rs:447]: `consumer_stats()` returns a single consumer stat by definition, hence here it's returning the first one. All consumer stats are accessible from the `MultipleConsumers` variant directly.

Comment (nazar-pc) [reply rust/src/router/consumer.rs:447]: Is `ConsumerStats::WithProducer` used anywhere now? Two entries meant consumer+producer before :thinking:

Comment (jmillan) [reply rust/src/router/consumer.rs:447]: Yes, `SimpleConsumer` and `SimulcastConsumer` returns the pair of recv-send streams stats.

Comment (nazar-pc) [reply rust/src/router/consumer.rs:447]: But with this PR there is nothing that ever constructs `ConsumerStats::WithProducer`. Should you check the kind of consumer and then produce either `ConsumerStats::WithProducer` or `ConsumerStats::MultipleConsumers` maybe?

**Comment by ibc** [comment]
Entry in rust changelog missing and after this we should release a rust version.

File: rust/src/router/consumer.rs (hunk 1 above)
Comment (jmillan) [reply rust/src/router/consumer.rs:447]: `MultipleConsumer` must remain. Yes, I'll create one or another based on the consumer type.

Comment (jmillan) [reply rust/src/router/consumer.rs:447]: Done

**Review by ibc — APPROVED** [review]
So the issue is fixed by this PR despite the ongoing discussion in the issue?

File: rust/tests/integration/consumer.rs [hunk 2]
```diff
@@ -679,6 +679,10 @@ fn consume_succeeds() {
                 video_pipe_consumer.app_data().downcast_ref::<()>().unwrap(),
                 &(),
             );
+            video_pipe_consumer
+                .get_stats()
+                .await
+                .expect("Failed to get consumer stats");
```
Comment (nazar-pc) [inline rust/tests/integration/consumer.rs:685]: Assuming this failed before the fix, looks good to me

**Review by nazar-pc — APPROVED** [review]

File: rust/tests/integration/consumer.rs (hunk 2 above)
Comment (jmillan) [reply rust/tests/integration/consumer.rs:685]: yes, it failed before.

**Comment by nazar-pc** [comment]
Adding enum variant is a breaking change. It is best to yank version 0.17.2 from crates.io and publish 0.18.0 to prevent breaking things for users. Also I'm wondering if new worker version should be releases too (likely also with a minor version bump) with some changes that happened recently.

**Comment by nazar-pc** [comment]
@jmillan in case you missed above message

**Comment by jmillan** [comment]
Done,

mediasoup-sys and mediasoup crates published. 0.17.2 version has been yanked.
