### PR TITLE
SeqManager: fix crash and add fuzzer

### LINKED ISSUE #1042: mediasoup-worker crash: free(): invalid pointer
## Bug Report

It's consistently happening in the demo server which is running very latest 3.11.19 version. No idea how to reproduce.

```
2023-03-30T10:06:18.320Z mediasoup:ERROR:Worker (stderr) free(): invalid pointer
2023-03-30T10:06:18.323Z mediasoup:ERROR:Worker worker process died unexpectedly [pid:3465, code:null, signal:SIGABRT]
```

### Your environment

- Operating system: Linux Debian
- gcc/clang version: 6.3.0
- mediasoup version: 3.11.19

### PR DESCRIPTION
**Pull request by jmillan**
Fixes #1042

### CODE REVIEW

File: worker/src/RTC/SeqManager.cpp [hunk 1]
```diff
@@ -113,15 +113,25 @@ namespace RTC
...
+		{
+			// New input is higher than the maximum seen. But less than acceptable units higher.
+			// Keep it as the maximum seen. See Drop().
+			if (IsSeqHigherThan(input, this->maxInput))
+				this->maxInput = input;
+
+			// New output is higher than the maximum seen. But less than acceptable units higher.
+			// Keep it as the maximum seen. See Sync().
+			if (IsSeqHigherThan(output, this->maxOutput))
+				this->maxOutput = output;
```
Comment (ibc) [inline worker/src/RTC/SeqManager.cpp]: Please let's add { } in all if/else conditions. I'm doing it little by little (there is a option for clang-tidy but it no longer works in my system due to rules that do not exist in the clang-tidy version that in theory we should use).

**Review by ibc — APPROVED** [review]

File: worker/src/RTC/SeqManager.cpp (hunk 1 above)
Comment (jmillan) [reply worker/src/RTC/SeqManager.cpp]: Do you know which one? we should remove it then.

File: worker/include/RTC/SeqManager.hpp [hunk 2]
```diff
@@ -49,6 +49,8 @@ namespace RTC
 		void ClearDropped();
 
 	private:
+		// Whether at least a sequence number has been inserted.
+		bool started{ false };
```
Comment (ibc) [inline worker/include/RTC/SeqManager.hpp:53]: Can you explain how it works? I usually hate those flags specially in stuff that deals with number series that can start with any random number.

**Review by ibc — APPROVED** [review]

File: worker/include/RTC/SeqManager.hpp (hunk 2 above)
Comment (jmillan) [reply worker/include/RTC/SeqManager.hpp:53]: The very first input value must become the current `maxInput` and `maxOutput`.

Before this flag:

* maxInput is initialized to `0` because it's a number.
* first call to `Insert(input)` arrives.
* `IsSeqHigherThan(input, this->maxInput)` => `IsSeqHigherThan(input, 0)` may be false, so `this-maxInput` remains the default value `0`, which is wrong.
* same for `maxOutput`

**Review by ibc — APPROVED** [review]

**Comment by ibc** [comment]
I'm releasing.

**Comment by ibc** [comment]
Deploying in the demo server as well.

**Comment by ibc** [comment]
3.11.20 published in a few minutes.
