### PR TITLE
Fix RTX packets containing non yet seen RTP packets being discarded

### LINKED ISSUE #906: consumer NACK with the specified sequence number packet but the retransmission fails
Hello, I want to inquire about a problem that NACK is sent but no retransmission succeed. 

The scenario is as follows: SDK pushes the stream to mediasoup server1, and mediasoup server2 receives this stream from mediasoup server1 and then restores the packet to a frame (mediasoup server2 as consumer and receive data through pipetransport).

When I set the packet loss rate to 10% (the rtt is small) in test enviroment, I found that mediasoup server2 would sometimes request a packet with a certain sequence number until it finally reached the maximum number of times, and mediasoup server1 received the NACK of this sequence number packet message, but the packet buffer of this sequence number was not found in the send buffer of the consumer. 

I continued to debug it and found that the problem is:

Suppose mediasoup server1 received RTP packets with sequence numbers 1, 2, 3, 4, and then received RTX packets with original sequence numbers 5 (the RTP packets with sequence numbers greater than 5 have not been received now), and later received RTP packet with sequence number 7. Because the sequence is out of order, nackGenerator will generate the NACK message of the seq=6 packet (the packet with the sequence number 5 will not be required to retransmit because it has been marked in the recoverList), but when the RTX packet with the original sequence number 5 is received, this sequence number is not in the In the nackList, so the packet with sequence number 5 was discarded and was not forwarded to the consumer (mediasoup server2). The seq=6 packet was finally retransmitted to the mediasoup server2 successfully, but the seq=5 packet was discarded, even if the mediasoup server2 kept requesting retransmission, it could not be retransmitted. 

image

I compared the processing logic of NackModule::OnReceivedPacket in nack_module.cc in webrtc, and found that in this case, webrtc just inserts the packet into the recoverList, does not require retransmission, but it does not discard the packet, and It is to continue to stuff data into the packetBuffer in RtpVideoStreamReceiver.

image

I would like to ask, what is the purpose of not forwarding this packet to consumers here? Is it better to return true here, thanks

### PR DESCRIPTION
**Pull request by ibc**
# Details

- Fixes #906.
- Credits to @penguinol and @mengbieting.
- Allow RTX packets containing non yet seen RTP seq numbers pass though.
- Accept RTX packets containing seq numbers in our NACK list despite the NACK was not sent yet.

## More info

The STR this PR fixes is the following:

1. Client sends RTP seq 1, mediasoup receives it.
2. Client sends RTP seq 2, mediasoup does NOT receive it.
3. Client sends a probation RTX packet that contain the original packet seq 2, mediasoup receives it.

In this case we want to accept that RTP packet with seq 2 received via RTX in bullet 2 rather than discarding it as we do in v3 branch before this PR.

## Notes

- I'm marking PR as draft until we finish the ongoing discussion in the issue #906.
- The code diff between what @penguinol uses and current mediasoup v3 is here: https://www.diffchecker.com/T6y4Osuz/

### CODE REVIEW

File: worker/src/RTC/NackGenerator.cpp [hunk 1]
```diff
@@ -68,22 +68,20 @@ namespace RTC
...
 				  packet->GetSsrc(),
 				  packet->GetSequenceNumber(),
 				  isRecovered ? "true" : "false");
 
-				auto retries = it->second.retries;
-
-				this->nackList.erase(it);
+				// NOTE: Even if we didn't send yet the NACK requesting this packet (this
+				// is, if nackInfo.retries == 0), we accept this packet and let it go
+				// through because we would request it later anyway.
```
Comment (jmillan) [inline worker/src/RTC/NackGenerator.cpp]: Little rewording which makes it more clear IMO.

```suggestion
				// NOTE: Accept the packet since it was in the `nackList`, regardless
				// the NACK requesting this packet was not sent yet (this is, if nackInfo.retries == 0)
				// because we would request it later anyway.
```

**Comment by jmillan** [comment]
I see it OK so far.

**Comment by ibc** [comment]
> I see it OK so far.

No no, see last comment in the related issue.
